### ISSUE TITLE
Cant open it use the arg python

### ISSUE THREAD

**Issue by schroef** [nutti/fake-bpy-module#1]
i want to try creating this on osx 10.11.6 using blender 2.78c
But i get a error for the arg --python
I get a list with all arguments i can use, the python argument is not there. Do you have any idea or solution to this?

**Comment by nutti** [comment]
@schroef 

did you get blender sources?
```gen.py``` needs blender sources.

If you want modules for 2.78c, I will make it.
Do you want?

**Comment by schroef** [comment]
Well after quite some googling it became clear that you need blender sources as well. Perhaps its good to add that to your read.me file. I was going crzay here;)

I got something working now using this video, https://www.youtube.com/watch?time_continue=1&v=L-JxGaDmZGs. I think those are the sources of 2.78 and not 2.78c

**Comment by nutti** [comment]
@schroef 

thanks.
i will add some description about this.

and i will generate modules for 2.78 or earlier.
please open this issue until other versions are supported.

**Comment by schroef** [comment]
> please open this issue until other versions are supported.
Sorry i dont get that line i think?

**Comment by nutti** [comment]
just i will support version 2.78

**Comment by nutti** [comment]
I added fake module for v2.78.
so close this issue.
