### ISSUE TITLE
No default values for bmesh.ops functions

### ISSUE THREAD

**Issue by MichaelMay81** [nutti/fake-bpy-module#10]
Why are there no default values for bmesh.ops functions?
e.g.:
bmesh.ops.extrude_face_region:
- fake-bpy-module: (bm, geom, edges_exclude, use_keep_orig, use_select_history)
- blender console: (bmesh, geom=[], edges_exclude={}, use_keep_orig=False, use_select_history=False)

or bmesh.ops.translate:
- fake-bpy-module: (bm, vec, space, verts)
- blender console: (bmesh, vec=Vector(), space=Matrix(), verts=[])

**Comment by nutti** [comment]
@MichaelMay81 

This fake module is generated from the `.rst` document.
We can not generate if `.rst` document will not be fixed.
Maybe we need to fix the `.rst` document included in Blender itself.

**Comment by nutti** [comment]
This bug is now fixed.  
But this is a temporary fix,.

The new pre-made module will be provided after some other bugs are fixed.
