### ISSUE TITLE
Collections are not usable

### ISSUE THREAD

**Issue by felixSchl** [nutti/fake-bpy-module#100]
**Expected behavior**  

I expected to be able to iterate over collections w/o running into type errors, however I am seeing this:

![image](https://user-images.githubusercontent.com/2703310/165485594-2acb51b1-37ac-4260-ab0e-2f6853deaa9f.png)

The problem is that the collection type is declared as a union as opposed to an intersection type. It's a bit more obvious in this error message:

![image](https://user-images.githubusercontent.com/2703310/165486181-71e8fa10-c43c-4912-9bb9-15ba8f17db8a.png)

I am new to mypy but from a bit of research it doesn't appear like they support intersection types just yet, but I played around with it and the desired type can be achieved by doing e.g.:

```python
class ObjectCollection(
    typing.Sequence[bpy.types.Object],
    typing.Mapping[str, bpy.types.Object],
    # HOWEVER, cannot enable these due to incompatible .items() declarations
    # bpy.types.SceneObjects,
    # bpy.types.bpy_prop_collection
):
    pass


objects: ObjectCollection = ...
o = objects.get("foo")
```

So I am not sure what's the best approach but it looks like we'd have to generate class stubs based off all the things that go into the union and resolve mismatches...

**Comment by nutti** [comment]
@felixSchl 

Current analysis algorithm does not support this kind of types.
I think this should be fixed.

**Comment by nutti** [comment]
I applied @MicaelJarniac 's suggestion.
Now, this issue is solved.
