### ISSUE TITLE
For operators, first unnamed parameter for custom context should be defined

### ISSUE THREAD

**Issue by anatawa12** [nutti/fake-bpy-module#103]
**System Information**
  
* OS: macOS
* Blender version: 2.93.9

**Expected behavior**  
*The behavior you expect about the feature you reported.*
```
bpy.ops.object.mode_set(bpy.context, mode='OBJECT')
```
Casuse no type errors

**Description about the bug**  
*The description about the bug.*
For all operators, there's a context parameter as the first parameter. see [Keywords and Positional Arguments](https://docs.blender.org/api/2.93/bpy.ops.html#keywords-and-positional-arguments)

**Screenshots/Files** [Optional]  
*It is good to solve the bug if you attach the screenshots or .blend file.*

**Additional comments** [Optional]

**Comment by nutti** [comment]
This issue is now fixed.
Fixed version will be included in next release.
