### ISSUE TITLE
bm.verts.new has incorrect type hint for co argument

### ISSUE THREAD

**Issue by cmbasnett** [nutti/fake-bpy-module#107]
**System Information**
  
* OS: Windows 11
* Blender version: 3.2.1

**Expected behavior**  
The type should be `(float, float, float)`, not `float`.

**Description about the bug**  
`bm.verts.new` has incorrect type hint for co argument (see: [documentation](https://docs.blender.org/api/current/bmesh.types.html?highlight=bm%20verts%20new#bmesh.types.BMVertSeq.new))

**Screenshots/Files** [Optional]  
![image](https://user-images.githubusercontent.com/5035660/183277031-3ee77e0e-6376-4a08-abd6-4cc624be76f8.png)

**Comment by nutti** [comment]
@cmbasnett 

Thanks.
This issue is now fixed.
