### ISSUE TITLE
bmesh.faces.new has incorrect argument type for verts

### ISSUE THREAD

**Issue by cmbasnett** [nutti/fake-bpy-module#109]
**System Information**
  
* OS: Windows 11
* Blender version: 3.2

**Expected behavior**  
`bmesh.faces.new` should expect an iterable type of `BMVert`

**Description about the bug**  
`bmesh.faces.new` only accepts a single `BMVert` as an argument, which is incorrect.

Oddly, the [documentation](https://docs.blender.org/api/current/bmesh.types.html?highlight=faces#bmesh.types.BMFaceSeq.new) for this function does not imply an iterable type.

**Screenshots/Files** [Optional]  
![image](https://user-images.githubusercontent.com/5035660/183839904-55b6a1c4-1578-49be-9919-bf1be656ba4c.png)

**Comment by nutti** [comment]
@cmbasnett 

I think this is a issue of the official documentation.
I will send a patch to fix the documentation.

**Comment by nutti** [comment]
Submitted the patch.
https://developer.blender.org/D15668

If this patch is merged, I think this issue will be fixed automatically.

**Comment by colinbasnettskyboxlabs** [comment]
Looks like this was approved :)

**Comment by nutti** [comment]
Thanks for pinging me.
I think the patch itself has not merged yet.
I will close this issue after the patch is merged.

**Comment by nutti** [comment]
The submitted patch is now merged.
