### ISSUE TITLE
Type annotations

### ISSUE THREAD

**Issue by MichaelMay81** [nutti/fake-bpy-module#11]
Is it possible to extract type annotations from blender and add them to the python stubs?

**Comment by nutti** [comment]
@MichaelMay81 

Could you give me an example about this issue?
The type annotation is already added in some module.
For example:
https://github.com/nutti/fake-bpy-module/blob/master/premade_modules/2.80/e5e885d0ecb9430a73e0a904cdb6035a2ef77e98/bgl.py#L1773

**Comment by MichaelMay81** [comment]
Ah, sorry. you are right!
