### ISSUE TITLE
EditBone does not implement __getitem__ or __setitem__

### ISSUE THREAD

**Issue by cmbasnett** [nutti/fake-bpy-module#110]
**System Information**
  
* OS: Windows
* Blender version: 3.2

**Expected behavior**  
`EditBone` should implement `__getitem__` and `__setitem__` since that type has custom properties editable via this interface.

This issue probably exists for a large number of other types as well (for example, `bpy.types.Object` also has the same problem).

**Screenshots/Files** [Optional]  
![image](https://user-images.githubusercontent.com/5035660/183844076-fad8c75a-e24c-4f6e-95f5-bb131ea4d6c7.png)

**Comment by nutti** [comment]
This issue is now fixed.
I think base class `bpy_struct` needs to include these functions.
