### ISSUE TITLE
EnumProperty constructor default argument does not accept string as argument

### ISSUE THREAD

**Issue by cmbasnett** [nutti/fake-bpy-module#111]
**System Information**
  
* OS: Windows
* Blender version: 3.2

**Expected behavior**  
The `EnumProperty` constructor's `default` argument should accept a `str`, `int` or `set[str]`, as per the [documentation](https://docs.blender.org/api/current/bpy.props.html?highlight=enumproperty#bpy.props.EnumProperty).

**Screenshots/Files** [Optional]  
![image](https://user-images.githubusercontent.com/5035660/183846160-79e84fff-ceba-4e3b-9f3e-ac61826405b1.png)

**Comment by nutti** [comment]
This issue is now fixed.
