### ISSUE TITLE
All vector and matrix variables return list of floats instead of Vector and Matrix types

### ISSUE THREAD

**Issue by cmbasnett** [nutti/fake-bpy-module#112]
**System Information**
  
* OS: Windows
* Blender version: 3.2

**Expected behavior**  
All vector types (e.g., `bpy.types.Object.location`) should return a `mathutils.Vector` type, and all matrix types (e.g., `bpy.types.Object.matrix_local`) should return a `mathutils.Matrix` type.

**Screenshots/Files** [Optional]  
![image](https://user-images.githubusercontent.com/5035660/183851088-b15b6798-45aa-4c0d-8bda-93332d448fbb.png)

**Additional comments** [Optional]

**Comment by nutti** [comment]
@cmbasnett 

The [actual document](https://docs.blender.org/api/current/bpy.types.Object.html#bpy.types.Object.location) does not show that return type is not `mathutils.Vector`.
I think this is a the official document's issue.
What do you think?

**Comment by colinbasnettskyboxlabs** [comment]
Yea, this is a documentation issue it seems. My guess is that they used to return just a list of list of floats, but it was never updated.

Out of curiosity, does the module get generated strictly from the documentation?

**Comment by nutti** [comment]
@colinbasnettskyboxlabs 

> does the module get generated strictly from the documentation?

Yes. fake-bpy-module generates from the documentation.
But we tweak some documentation on the generation process.

I think this issue is related to #93 #95 #99, and tackle to this issue now.

**Comment by nutti** [comment]
This issue is now fixed at the same time of #93 .
