### ISSUE TITLE
mathutils.Matrix.Scale expects optional axis argument to be filled

### ISSUE THREAD

**Issue by cmbasnett** [nutti/fake-bpy-module#113]
**System Information**
  
* OS: Windows 11
* Blender version: 3.2

**Expected behavior**  
The `axis` argument to `mathutils.Matrix.Scale` should be optional.

**Description about the bug**  
The `axis` argument is listed as requiring a `Vector` type, but it should be an `Optional[Vector]` type.

**Screenshots/Files**
![image](https://user-images.githubusercontent.com/5035660/184285154-b4e1c6b2-e4aa-4a01-8455-2cfd6f518109.png)

**Comment by nutti** [comment]
Fixed this issue.
