### ISSUE TITLE
Where is located the path of the fake-bpy-module python completion for workspace.json ?

### ISSUE THREAD

**Issue by softyoda** [nutti/fake-bpy-module#116]
**System Information**
* OS: Windows
* VS-code

In this [page ](https://github.com/nutti/fake-bpy-module/blob/master/docs/setup_visual_studio_code.md)it says to add the path to the "generated modules" under python.autoComplete.extraPaths. 

Where do I find this path ? I installed fake-bpy-module using pip.

**Comment by nutti** [comment]
@softyoda 

You don't need to add path to the "generated modules" when you install module by using pip.
The referred document assumes when you generate module manually.

**Comment by nutti** [comment]
Close this issue because of the no reaction.
Reopen if there is still a problem.
