### ISSUE TITLE
bpy.types.Scene missing objects

### ISSUE THREAD

**Issue by MichaelMay81** [nutti/fake-bpy-module#12]
Shouldn't the type bpy.types.Scene have an objects property to link objects to the scene?

e.g.,
def get_scene() -> bpy.types.Scene:
  return bpy.context.scene

get_scene().objects.link(obj)

**Comment by MichaelMay81** [comment]
Also, bpy.types.Material is missing texture_slots

**Comment by nutti** [comment]
@MichaelMay81 

> Shouldn't the type bpy.types.Scene have an objects property to link objects to the scene?

I think this is not correct.
`bpy.types.Object` does not have any `link` method.

https://docs.blender.org/api/blender2.8/bpy.types.Object.html#bpy.types.Object

> Also, bpy.types.Material is missing texture_slots

I think it is no problem.
Blender 2.8 does not have `texture_slots` in `bpy.types.Matrial`.

https://docs.blender.org/api/blender2.8/bpy.types.Material.html

**Comment by MichaelMay81** [comment]
bpy.types.Scene.objects is of type SceneObjects and this has a link function.
https://docs.blender.org/api/current/bpy.types.SceneObjects.html#bpy.types.SceneObjects

**Comment by MichaelMay81** [comment]
Oh and I forgot to say, that I am using Blender 2.79

**Comment by nutti** [comment]
@MichaelMay81 

I checked `SceneObjects` and I found there is already `link` and `unlink` method in the modules for every version.
It seems there is no issue about it.

**Comment by nutti** [comment]
> Also, bpy.types.Material is missing texture_slots

This one is fixed. Thanks for your report.
