### ISSUE TITLE
bpy_prop_collection is missing `__len__`

### ISSUE THREAD

**Issue by angavrilov** [nutti/fake-bpy-module#120]
### System Information

* OS: Windows
* IDE: PyCharm
* Version: fake_bpy_modules_3.3-20221006

### Description about the bug

The `bpy_prop_collection` class doesn't have a `__len__` method, which causes PyCharm to complain about any uses of `len(...)` on collections. The actual collections in the blender python console have `__len__` in `dir`.  Manually editing the file to add `__len__` fixes it.

Edit: the `Matrix` type also supports `len` in practice - it returns the matrix size, i.e. 3 for 3x3, 4 for 4x4.

**Comment by nutti** [comment]
This issue is now fixed.
