### ISSUE TITLE
Quaternion rotate function argument type is incorrect

### ISSUE THREAD

**Issue by cmbasnett** [nutti/fake-bpy-module#122]
### System Information

* OS: Windows 11
* Blender version: 3.3

### Expected behavior

The `other` argument type for the [Quaternion.rotate](https://docs.blender.org/api/current/mathutils.html?highlight=rotate#mathutils.Quaternion.rotate) function should accept an `Euler`, `Quaternion` or `Matrix` type.

### Description about the bug

The argument only accepts an `Euler` type.

### Screenshots/Files [Optional]

![image](https://user-images.githubusercontent.com/5035660/200475181-7c5fefb2-d4f3-4659-84a7-87c63dbb81e1.png)

**Comment by nutti** [comment]
Fixed this issue.
