### ISSUE TITLE
IDMaterials append should accept `None` as a valid argument

### ISSUE THREAD

**Issue by cmbasnett** [nutti/fake-bpy-module#127]
### System Information

* OS: Windows 11
* Blender version: 3.4.0

### Expected behavior

IDMaterials.append should accept `None` as an argument (i.e., `Optional[Material]`). Passing `None` as an argument adds an empty material slot.

### Description about the bug

This is probably just a documentation issue. The documentation should be updated to reflect that it can accept a `None` argument.

### Screenshots/Files [Optional]

![image](https://user-images.githubusercontent.com/5035660/209275120-dc09848d-31ba-4f0f-a817-03aa8710038a.png)

**Comment by nutti** [comment]
@cmbasnett 

Thanks.
I'm wondering about the handling of `Nullable` arugment.
From the discussion, it seems that all parameters without `(Never None)` can allow `None`.
https://github.com/nutti/fake-bpy-module/issues/121#issuecomment-1338900563

It helps me a lot if you share the method to distinguish between `non-Nullable` argument and `Nullable` argument.

**Comment by nutti** [comment]
This issue is now fixed.
