### ISSUE TITLE
Missing type annotations for bpy.app.handlers

### ISSUE THREAD

**Issue by JonathanPlasse** [nutti/fake-bpy-module#128]
Hi,
Love what you have done with `fake-bpy-module`.
The handlers inside `bpy.app.handlers` are of the type `List[Callable[[bpy.typse.Scene], None]` but do not have a type in `fake-bpy-module`.
How could these type annotations be added?

**Comment by nutti** [comment]
Sorry for late response.

This issue is now resolved.

**Comment by JonathanPlasse** [comment]
Awesome, thanks!
