### ISSUE TITLE
Doesn't work (VS Code, Blender 2.8)

### ISSUE THREAD

**Issue by ogierm** [nutti/fake-bpy-module#13]
**System Information**
  
* OS: Windows 10 1803
* Blender 2.8
* Editor: VS Code

**Expected behavior**  
I guess in an ideal world it would work

**Description about the bug**  
I followed the instructions, but the Python addon still can't find the bpy module.

**Screenshots/Files**
![image](https://user-images.githubusercontent.com/29630575/54126762-9b73de80-4408-11e9-89b9-c905dac1efd7.png)

![image](https://user-images.githubusercontent.com/29630575/54126980-0de4be80-4409-11e9-8d8e-af8ee867831d.png)

**Comment by riccardobl** [comment]
Hey, this worked for me https://github.com/Microsoft/vscode-python/issues/2791#issuecomment-427061067

**Comment by ColinConwell** [comment]
I followed the instructions in the link and now am receiving the pylint error Module 'bpy' has no 'context' member. Did you get something similiar?

**Comment by nutti** [comment]
In my environment, it works correctly with follwing the instruction.
https://github.com/nutti/fake-bpy-module/blob/master/docs/setup_visual_studio_code.md

My environment is same as @ogierm .
I'm not sure what is the problem about this issue.

**Comment by ColinConwell** [comment]
It appears the autocomplete is working correctly, but pylint is throwing an error where it doesn't seem to recognize that bpy.context.scene is a valid bit of code (thus the module 'bpy' has 'context' member error). Have you experienced similar errors with pylint?

**Comment by riccardobl** [comment]
Yes,i have the same issue with bpy.context. I assume this is still valid: https://github.com/nutti/fake-bpy-module/issues/6

This is my .env
`PYTHONPATH=/DEV/fake-bpy-module/premade_modules/2.80/e5e885d0ecb9430a73e0a904cdb6035a2ef77e98/`

**Comment by nutti** [comment]
@riccardobl @ColinConwell 

Thanks. I understand the problem.
`bpy.context` is changed dynamically, so we can not infer its member variable as I mentioned at #6 .
This is beyond the limitation of this fake module.

If there is no other problem, I would like to discuss at #6 about this.
I will rethink to be able to complete code about `bpy.context` in future.

**Comment by nutti** [comment]
By the way, I found the method to suppress the pylint error on dynamic attributes.

https://python-projects.logilab.narkive.com/7C2qY6ot/is-there-a-way-to-tell-pylint-about-dynamic-attributes

For now, it is difficult to complete the code, but this makes us to suppress the pylint error.
Until #6 is fixed, I will adopt this patch to `bpy.context`

**Comment by nutti** [comment]
Temporary fix patch is now on master branch. so I close this issue now.
Rest of the issue will be discussed in #6 .
