### ISSUE TITLE
Object.children should be tuple

### ISSUE THREAD

**Issue by Pyrolistical** [nutti/fake-bpy-module#130]
### System Information

* OS: Windows 11 64-bit
* Python: 3.10.11
* Blender: 3.5

### Expected behavior

`bpy.types.Object.children` should be iterable

From Blender console:
```
>>> type(bpy.data.objects['some object'])
<class 'bpy_types.Object'>

>>> type(bpy.data.objects['some object'].children)
<class 'tuple'>
```

### Description about the bug

in fake-bpy-modules/bpy/types.py `class Object` defines `children` as:
```
children = None
```

### Additional comments
I believe it should be `Tuple[Object]` as the workaround is to cast children

```python
from typing import cast

for child in cast(tuple[Object], some_object.children):
```

**Comment by nutti** [comment]
This issue needs to be fixed by sending a patch to Blender itself.
I have already submitted the PR.
https://projects.blender.org/blender/blender/pulls/108852

**Comment by nutti** [comment]
This issue is now solved.
