### ISSUE TITLE
Object.data should be Mesh

### ISSUE THREAD

**Issue by Pyrolistical** [nutti/fake-bpy-module#131]
### System Information

* OS: Windows 11 64-bit
* Python: 3.10.11
* Blender: 3.5

### Expected behavior

`bpy.types.Object.data` should be of type `bpy.types.Mesh`

From Blender console:
```
>>> type(bpy.data.objects['some object'])
<class 'bpy_types.Object'>

>>> type(bpy.data.objects['some object'].data)
<class 'bpy_types.Mesh'>
```

### Description about the bug

in fake-bpy-modules/bpy/types.py `class Object` defines `data` as:
```
data: 'ID' = None
```

### Additional comments
I believe it should be `Mesh` as the workaround is to cast data

```python
from typing import cast

mesh = cast(Mesh, some_object.data)
bpy.data.meshes.remove(mesh, do_unlink=True)
```

**Comment by nutti** [comment]
`bpy.types.Object.data` depends on the type of object (i.e. `bpy.types.Camera` for Camera object`.
So, cast is needed for this case.
