### ISSUE TITLE
Object.rotation_euler components should be mutable

### ISSUE THREAD

**Issue by Pyrolistical** [nutti/fake-bpy-module#132]
### System Information

* OS: Windows 11 64-bit
* Python: 3.10.11
* Blender: 3.5

### Expected behavior

`bpy.types.Object.rotation_euler` is a vector of 3 components, each of which should be modifiable

From Blender console:
```
>>> type(bpy.data.objects['some object'])
<class 'bpy_types.Object'>

>>> type(bpy.data.objects['some object'].rotation_euler)
<class 'Euler'>

>>> bpy.data.objects['some object'].rotation_euler[0] = 1.5
>>> bpy.data.objects['some object'].rotation_euler[0]
1.5
```

Observe `some object` is rotated about 90 degrees around x-axis.

### Description about the bug

in fake-bpy-modules/bpy/types.py `class Object` defines `rotation_euler` as:
```
rotation_euler: typing.Union[
    bpy_prop_array[float], typing.Sequence[float], typing.
    Tuple[float, float, float], 'mathutils.Vector'] = None
```
When attempting to set it, pylance gives the following 2 errors:
```
"__setitem__" method not defined on type "Sequence[float]"
"__setitem__" method not defined on type "Tuple[float, float, float]"
```

### Additional comments
The workaround is to just add `#type: ignore` to the line

**Comment by nutti** [comment]
This issue is now fixed.
