### ISSUE TITLE
VS Code warnings on poll_message_set

### ISSUE THREAD

**Issue by Andrej730** [nutti/fake-bpy-module#133]
### System Information
* System: Windows 11, VS Code
* fake-bpy-module-latest

Noted some issue causing warnings atleast in VS Code. Since all modules are pre-generated I guess it could lead to more general issue.

poll_message_set - add classmethod. VS Code problem: "Argument missing for parameter "message""
![image](https://user-images.githubusercontent.com/9417531/232279961-deb9ead4-31b1-46b8-bbc0-d3966b8a1ecf.png)

What helps is changing code in types.py from 
```python
    def poll_message_set(self, message: typing.Optional[str], *args):
        ''' Set the message to show in the tool-tip when poll fails. When message is callable, additional user defined positional arguments are passed to the message function.

        :param message: The message or a function that returns the message.
        :type message: typing.Optional[str]
        '''
        pass
```
to
```python
    @classmethod
    def poll_message_set(self, message: typing.Optional[str], *args):
        ''' Set the message to show in the tool-tip when poll fails. When message is callable, additional user defined positional arguments are passed to the message function.

        :param message: The message or a function that returns the message.
        :type message: typing.Optional[str]
        '''
        pass
```

**Comment by nutti** [comment]
This issue needs to be fixed from Blender.
I have submitted the PR to fix this issue.
https://projects.blender.org/blender/blender/pulls/108854

**Comment by nutti** [comment]
The patch is now merged.
I will close this issue.
