### ISSUE TITLE
Matrix.LocRotScale rotation argument missing None

### ISSUE THREAD

**Issue by Road-hog123** [nutti/fake-bpy-module#134]
### System Information

* OS: Windows 10 22H2
* Blender: 3.5.1
* Python: 3.10.9
* `fake-bpy-module-3.4` from pypi

### Expected Behavior

The typing for `mathutils.Matrix.LocRotScale` matches [the documention](https://docs.blender.org/api/3.5/mathutils.html#mathutils.Matrix.LocRotScale), with a `rotation` argument typed `Matrix | Quaternion | Euler | None`.

### Actual Behaviour

```python
(method) def LocRotScale(
    location: Vector | None,
    rotation: Sequence[float] | Quaternion | Euler,
    scale: Vector | None
) -> Matrix
```
```text
Argument of type "Euler | None" cannot be assigned to parameter "rotation" of type "Sequence[float] | Quaternion | Euler" in function "LocRotScale"
  Type "Euler | None" cannot be assigned to type "Sequence[float] | Quaternion | Euler"
    Type "None" cannot be assigned to type "Sequence[float] | Quaternion | Euler"
      Type "None" cannot be assigned to type "Sequence[float]"
      Type "None" cannot be assigned to type "Quaternion"
      Type "None" cannot be assigned to type "Euler"
```
`LocRotScale(None, None, None)` shouldn't raise any type errors—it returns a 4x4 identity matrix:
```pycon
>>> Matrix.LocRotScale(None, None, None) == Matrix.Identity(4)
True
```

### Additional comments

`Object.location`, `.rotation_euler`, `.rotation_quaternion` and `.scale` are Unions of `List`s and `Tuple`s of `float`s in addition to their Mathutils types, which means that passing them to `LocRotScale` raises yet further type errors—is this by design, or a separate issue that I should create an issue for? These are certainly not the only places these Union types are used for Mathutils types.

**Comment by nutti** [comment]
Fixed this issue now.
