### ISSUE TITLE
SpaceView3D.draw_handler_add/remove self argument not implicit

### ISSUE THREAD

**Issue by Rawalanche** [nutti/fake-bpy-module#137]
### System Information

* OS: Windows
* Blender version: 3.6.0

### Description about the bug
Hi, I installed fake-bpy and was able to get my script to be nearly warning/error clean even with linter as strict as PyLint. However I have issue with two specific functions: bpy.types.SpaceView3D.draw_handler_add and bpy.types.SpaceView3D.draw_handler_remove. I have no clue why, but they keep causing the "no value for argument errors:
![image](https://github.com/nutti/fake-bpy-module/assets/38806207/8b009e8a-2ebf-463e-accd-01b64c7b58a1)
and if I specify the argument names, the linter starts complaining about not supplying self as an argument, while self in this case should be implicit:
![image](https://github.com/nutti/fake-bpy-module/assets/38806207/a2e5d53b-6afa-4db2-b054-1ec842c6c4c7)

Is this a bug or am I doing something wrong? I don't believe I should be supplying any self argument here, as that one should be passed by Python implicitly... or not?

**Comment by nutti** [comment]
This is an issue that comes from handling `draw_handler_add` and `draw_handler_remove` as methods not class methods.

This issue needs to be fixed from Blender.
I have submitted the PR to fix this issue.
https://projects.blender.org/blender/blender/pulls/111107

**Comment by Rawalanche** [comment]
> This is an issue that comes from handling `draw_handler_add` and `draw_handler_remove` as methods not class methods.
> 
> This issue needs to be fixed from Blender. I have submitted the PR to fix this issue. https://projects.blender.org/blender/blender/pulls/111107

Ah, thanks! Great job by the way. I am using latest fake-bpy and as I said, even with strict linters, I can get a lot of static analysis and code completion in VSCode without having to ignore any errors and warnings.

**Comment by nutti** [comment]
The patch is merged.
