### ISSUE TITLE
mathutils `freeze()` incorrectly returns `None`

### ISSUE THREAD

**Issue by Road-hog123** [nutti/fake-bpy-module#139]
The `freeze()` staticmethods of `Color`, `Vector`, `Matrix`, `Euler` and `Quaternion` have no return type defined, so are implicitly typed as returning `None` instead of a frozen copy of the object.

The reason for this is that Blender uses the same method for all these classes and therefore the [same documentation](https://projects.blender.org/blender/blender/src/commit/08eb7f1c970d4ccc47382ebed210acd92d1336d2/source/blender/python/mathutils/mathutils.cc#L676-L683), which therefore includes a generic "An instance of this object." return type.

I don't know C so I can't tell how easy it would be to change Blender's source to make this documentation more specific, but perhaps if it's not practical a patch can be applied in this module.

**Comment by nutti** [comment]
This issue is now fixed.
