### ISSUE TITLE
EnumProperty items does not accept tuples

### ISSUE THREAD

**Issue by cmbasnett** [nutti/fake-bpy-module#140]
### System Information

* OS: Windows 11
* Blender version: 4.0.0

### Expected behavior

The `items` property in `EnumProperty` should accept an `Iterable` of the items (e.g., passing a tuple is valid, but the type hints flags it as an error.

### Description about the bug

I have the following:

```
csg_operation_items = (
    ('CSG_Add', 'Add', 'Add to world', 1),
    ('CSG_Subtract', 'Subtract', 'Subtract from world', 2),
)
```

And the following usage:

```
    csg_operation: EnumProperty(
        name='CSG Operation',
        description='The CSG operation to perform when this brush is applied to the world',
        items=csg_operation_items,
        default='CSG_Add',
        update=bsp_brush_update,
        options=empty_set
    )
```

The error I get is:

```
Expected type 'list[tuple[str, str, str]] | (...) -> Any | None', got 'tuple[tuple[str, str, str, int], tuple[str, str, str, int]]' instead
```

### Screenshots/Files [Optional]

![image](https://github.com/nutti/fake-bpy-module/assets/5035660/7ead2976-ea36-4b6f-9ec5-864e1e10606d)

### Additional comments [Optional]

In addition, the items themselves can actually have up to 5 elements `(id, name, description, icon, num)`, but the type hinting only expects 3.

**Comment by nutti** [comment]
This issue is now fixed.
