### ISSUE TITLE
Layout.prop data argument should be object, not AnyType

### ISSUE THREAD

**Issue by cmbasnett** [nutti/fake-bpy-module#141]
### System Information

* OS: Windows 11
* Blender version: 4.0

### Expected behavior

`Layout.prop` should accept an `object` as the first argument type.

### Description about the bug

The `Layout.prop` has it's `data` type as  `AnyType`, which gives errors when passing in `self`, for example.

### Screenshots/Files [Optional]

![image](https://github.com/nutti/fake-bpy-module/assets/5035660/63021ffd-0991-41a8-b74c-411be54cffa0)

### Additional comments [Optional]

There is also the same problem with `prop_search` for both the `data` and `search_data` arguments.

**Comment by nutti** [comment]
This issue is now fixed.
