### ISSUE TITLE
mathutils.Matrix types do not implement __getitem__

### ISSUE THREAD

**Issue by cmbasnett** [nutti/fake-bpy-module#142]
### System Information

* OS: Windows 11
* Blender version: 4.0

### Expected behavior

Accessing or assigning to `Matrix` objects using the `[]` operators should not result in type errors.

### Description about the bug

`Matrix` does not implement `__getitem__`, so using the `[]` operator results in a typing error.

### Screenshots/Files [Optional]

![image](https://github.com/nutti/fake-bpy-module/assets/5035660/f857a284-3300-4be7-9654-90e1c1461f43)

**Comment by nutti** [comment]
This issue is now fixed.
