### ISSUE TITLE
BMesh.edges is not iterable

### ISSUE THREAD

**Issue by cmbasnett** [nutti/fake-bpy-module#143]
### System Information

* OS: Windows 11
* Blender version: 4.0

### Expected behavior

BMesh.edges, faces etc. should all be iterable.

### Description about the bug

Trying to use `Bmesh.edges` in a loop like:

```for edge in bm.edges:```

Results in a typing error (see screenshot).

### Screenshots/Files [Optional]

![image](https://github.com/nutti/fake-bpy-module/assets/5035660/c38f6f38-8e69-4739-92bb-1fe8cd105aa1)\

### Additional comments [Optional]

All of the `*Seq` types should implement the `Iterable` trait.

**Comment by nutti** [comment]
This issue is now fixed.
