### ISSUE TITLE
Operator does not implement report function

### ISSUE THREAD

**Issue by cmbasnett** [nutti/fake-bpy-module#144]
### System Information

* OS: Windows
* Blender version: 4.0

### Expected behavior

The `report` function should be implemented for the `Operator` type.

### Description about the bug

The `report` function is missing for the `Operator` type.

### Screenshots/Files [Optional]

![image](https://github.com/nutti/fake-bpy-module/assets/5035660/1a409434-037d-40c6-9550-c511018e4ceb)

**Comment by nutti** [comment]
@cmbasnett 

This is wired to me.
Function `report` is defined in the `bpy.types.Operator` class like this.

```
    def report(self, type: typing.Optional[
            typing.Union[typing.Set[str], typing.Set[int]]],
               message: typing.Union[str, typing.Any]):
        ''' report

        :param type: Type
        :type type: typing.Optional[typing.Union[typing.Set[str], typing.Set[int]]]
        :param message: Report Message
        :type message: typing.Union[str, typing.Any]
        '''
        pass
```

**Comment by nutti** [comment]
@cmbasnett 

Any update for above comment?

**Comment by cmbasnett** [comment]
Sorry, I just looked into it and this was my own fault. I was importing `bpy_types.Operator`, not `bpy.types.Operator` 😢
