### ISSUE TITLE
BMVertSeq does not implement __getitem__

### ISSUE THREAD

**Issue by cmbasnett** [nutti/fake-bpy-module#145]
### System Information

* OS: Windows 11
* Blender version: 4.0

### Expected behavior

`BMVertSeq` should implement `__getitem__` (e.g., `bm.verts[2]`).

### Description about the bug

Trying to use the `[]` operator on a BMVertSeq results in a typing error.

### Screenshots/Files [Optional]

![image](https://github.com/nutti/fake-bpy-module/assets/5035660/17ba6b6e-dc3e-4625-b043-6c59bb09f65c)

### Additional comments [Optional]

This is likely a similar problem for faces, edges etc.

**Comment by nutti** [comment]
This issue can be solved by solving issue #143.

**Comment by nutti** [comment]
This issue is now fixed.
