### ISSUE TITLE
BMFaceSeq.new should accept Iterable, not Sequence

### ISSUE THREAD

**Issue by cmbasnett** [nutti/fake-bpy-module#146]
### System Information

* OS: Windows 11
* Blender version: 4.0

### Expected behavior

I should be able to use a `map` iterator as an argument to `bm.faces.new`.

### Description about the bug

Only lists and tuples work for arguments, but any iterable should be accepted.

### Screenshots/Files [Optional]

![image](https://github.com/nutti/fake-bpy-module/assets/5035660/67fa3998-a015-412e-9eb1-7948c7d2c2c4)

### Additional comments [Optional]

**Comment by nutti** [comment]
This issue is now fixed.
