### ISSUE TITLE
bpy.utils.unregister_class() is not typed

### ISSUE THREAD

**Issue by JonathanPlasse** [nutti/fake-bpy-module#149]
Hi

`register_class()` is typed
```python
def register_class(cls: typing.Optional[typing.Any]):
    ''' Register a subclass of a Blender type class. :raises ValueError: if the class is not a subclass of a registerable blender class.

    :param cls: `bpy.types.Panel`, `bpy.types.UIList`, `bpy.types.Menu`, `bpy.types.Header`, `bpy.types.Operator`, `bpy.types.KeyingSetInfo`, `bpy.types.RenderEngine`
    :type cls: typing.Optional[typing.Any]
    '''

    pass
```
but not `unregister_class()`
```python
def unregister_class(cls):
    ''' Unload the Python class from blender. If the class has an *unregister* class method it will be called before unregistering.

    '''

    pass
```

It trigger the error pyright [`reportUnknownMemberType`](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportUnknownMemberType)

As `unregister_class()` is the mirror function of `register_class()` would it be possible to type it the same?

**Comment by nutti** [comment]
This issue need to be fixed from Blender source code.
https://github.com/blender/blender/blob/9c0bffcc89f174f160805de042b00ae7c201c40b/source/blender/python/intern/bpy_rna.cc#L9089-L9095

**Comment by nutti** [comment]
Created the PR for this issue.
https://projects.blender.org/blender/blender/pulls/114523

**Comment by nutti** [comment]
The patch is now merged.

**Comment by JonathanPlasse** [comment]
Thank you
