### ISSUE TITLE
bpy.types.Panel.poll() return type should bool

### ISSUE THREAD

**Issue by JonathanPlasse** [nutti/fake-bpy-module#150]
As mentionned in the [`Panel.poll()`](https://docs.blender.org/api/current/bpy.types.Panel.html#bpy.types.Panel.poll) documentation the return type should be `bool`.

Currently, the return type is leaved blank which Pyright interprets as `None` instead.
```python
    @classmethod
    def poll(cls, context: 'Context'):
        ''' If this method returns a non-null output, then the panel can be drawn

        :param context: 
        :type context: 'Context'
        '''
        pass
```

**Comment by nutti** [comment]
This issue is now fixed.

**Comment by JonathanPlasse** [comment]
Thank you very much.
