### ISSUE TITLE
Many type errors when using bmesh

### ISSUE THREAD

**Issue by Intrets** [nutti/fake-bpy-module#152]
### System Information

* OS: Windows
* Blender version: 3.6

### Expected behavior

Ability to use type information in Pycharm or VSCode's Pylance.

### Description about the bug

For types from bmesh I ran into a lot of type errors.

### Screenshots/Files

Pylance errors, similar errors in pycharm:

<details>

<summary>code in text format</summary>

```python
import bpy
import bmesh

for mesh in bpy.data.meshes:
    mesh.animation_data
    bm = bmesh.from_edit_mesh(mesh)
    bm.verts.ensure_lookup_table()
    vert = bm.verts[0]
    vert.co.x += 2.0

    bmesh.ops.triangulate(bm, faces = bm.faces) 
    bmesh.update_edit_mesh(mesh)

    for face in bm.faces:
        for vert in face.verts:
            print(vert.index)

    bm.to_mesh(mesh)
    bm.free()

```

</details>

![image](https://github.com/nutti/fake-bpy-module/assets/9140942/d653335a-0e35-4f22-afdb-cf1024e12850)
![image](https://github.com/nutti/fake-bpy-module/assets/9140942/93fda283-bf7a-4636-902e-989ec320f7ab)

### Additional comments

Am I misunderstanding the scope of the project? From the small tests I did I could use the types fine for bpy types, iterating over them, passing to function arguments etc. but when I tried using some bmesh functions and types it went wrong.

**Comment by nutti** [comment]
This issue is fixed now.
