### ISSUE TITLE
bpy_prop_collection.get() return type should be Optional[GenericType]

### ISSUE THREAD

**Issue by JonathanPlasse** [nutti/fake-bpy-module#153]
Hi,
`bpy_prop_collection.get()` does not currently have a return type.
It should be `Optional[GenericType]`.

**Comment by nutti** [comment]
This issue is now fixed.

**Comment by Road-hog123** [comment]
The return type should be `GenericType | DefaultType`; `Optional[GenericType]` is only correct if `default` is `None`:

`collection.get('missing', collection[0])` should type as `GenericType`  
`collection.get('missing', 'example')` should type as `GenericType | str`

**Comment by nutti** [comment]
@Road-hog123 

How should we represent `DefaultType` in the type annotation?

**Comment by Road-hog123** [comment]
Like this I think?
```py
DefaultType = typing.TypeVar("DefaultType")

def get(self, key: str | None, default: DefaultType=None) -> GenericType | DefaultType:
    ...
```

**Comment by nutti** [comment]
@Road-hog123 

Thanks. Fixed this now.
