### ISSUE TITLE
bpy_prop_collection.__getitem__() should accept slice too

### ISSUE THREAD

**Issue by JonathanPlasse** [nutti/fake-bpy-module#154]
`bpy_prop_collection.__getitem__()` can use slice, but is not present in the type hint.
```python
def __getitem__(self, key: typing.Optional[typing.Union[int, str]]
                    ) -> 'GenericType':
        ''' 

        :param key: 
        :type key: typing.Optional[typing.Union[int, str]]
        :rtype: 'GenericType'
        '''
        ...
```
Adding `slice` would fix this issue.
```python
def __getitem__(self, key: typing.Optional[typing.Union[int, str, slice]]
                    ) -> 'GenericType':
        ''' 

        :param key: 
        :type key: typing.Optional[typing.Union[int, str, slice]]
        :rtype: 'GenericType'
        '''
        ...
```
To fix this, should Blender documentation be updated?

**Comment by nutti** [comment]
This issue is fixed now.

**Comment by JonathanPlasse** [comment]
Yes, it is.
It has been done for mathutils matmul operators.
https://github.com/nutti/fake-bpy-module/blob/1f540cf284a04e09bc36e6766fc911d7cc7a3eec/src/mods/common/analyzer/append/mathutils.mod.rst?plain=1#L135-L150
