### ISSUE TITLE
Would you like some help maintaining this project?

### ISSUE THREAD

**Issue by JonathanPlasse** [nutti/fake-bpy-module#160]
Hello,
I love your project.

I have been using it extensively in my add-on development. The combination with Pyright has greatly enhanced my development workflow with auto-completion and type-checking.
Over the past year, I had to use a lot of `pyright: ignore` and `typing.cast()` to bypass typing errors.
In order to fix these typing issues, I opened a lot of issues to fix and improve the typing, and a lot more are coming.
I would like to propose my help to maintain this project to keep it up to date and improve the typing for a better developer experience.

Thank you for your dedication to maintaining this valuable resource for the Blender development community.

Cheers,
Jonathan

**Comment by nutti** [comment]
Good news!
The main issue of this project is a lack of maintainers or contributors.
So, it is helpful for me if you maintain this project.

I think the code which generates the .pyi stub file, is a bit complicated for you to understand without my help for the first time.
If you want to tackle the maintainance of this project, I will support you until you understand the whole code structure.

How do you think?

**Comment by JonathanPlasse** [comment]
Thank you for the positive feedback. I agree the codebase is complex and plan to start addressing the issues I've raised, from simpler to more complex, to better understand it.

I propose setting up a GitHub discussion for centralized communication about the codebase. This will help in problem-solving and in updating the CONTRIBUTING.md to guide new contributors.

Looking forward to collaborating and enhancing the project.

**Comment by nutti** [comment]
Great.
Yes, it is better to start from solving your issue.

You can create the discussion on GitHub.
After you create a discussion, I will follow you.
Thanks for your suggestion.

**Comment by nutti** [comment]
@JonathanPlasse 

> I propose setting up a GitHub discussion for centralized communication about the codebase. This will help in problem-solving and in updating the CONTRIBUTING.md to guide new contributors.

About this, you can create a new discussion.
https://github.com/nutti/fake-bpy-module/discussions

I will wait to solve your created issue.
But, could you tell me what are you going to tackle at first?
If you share the current status, we can avoid conflicting the issue to tackle.

**Comment by JonathanPlasse** [comment]
I would like to start with all `bpy_prop_collection` related issues.
I should have some time for it this Sunday.

**Comment by nutti** [comment]
@JonathanPlasse 

OK. Then, I will not touch these issues.

BTW, are you going to make a GitHub discussion?
If a new discussion is created, I will close this issue.

**Comment by nutti** [comment]
The discussion is started in GitHub discussion.
I will close this issue for now.
