### ISSUE TITLE
bpy_prop_array property regression

### ISSUE THREAD

**Issue by JonathanPlasse** [nutti/fake-bpy-module#162]
- The resolution of #132 cause a regression in my code

The following code does not pass Pyright or MyPy.

```python
import bpy

bpy.context.active_object.parent_vertices = [1, 2, 3]
```

- This could be solved with the same solution mentionned in #158

**Comment by nutti** [comment]
@JonathanPlasse 

Can we close this issue by #158 is closed?

**Comment by JonathanPlasse** [comment]
#158 was for `mathutils` not `bpy_prop_array`.
I will make a PR.

**Comment by nutti** [comment]
@JonathanPlasse Great, Thanks!
