### ISSUE TITLE
Avoid "Call expression not allowed in type expression" in property declarations

### ISSUE THREAD

**Issue by UuuNyaa** [nutti/fake-bpy-module#164]
This issue will be **impossible** to solve because this code style is a proprietary type semantics extension of Blender.

### Description about the feature
Lint succeeds with the following code:
```python
class TestGroupProperty(bpy.types.PropertyGroup):
    test_float_property: bpy.props.FloatProperty(name="test float property", default=0.0)
```

#### Actual
![image](https://github.com/nutti/fake-bpy-module/assets/70152495/3ed7cbc5-1b7e-4d31-800b-d0243384fc4a)

#### Expected
No errors.

### Are you willing to contribute about this feature. (Yes/No)
Neither

**Comment by nutti** [comment]
@UuuNyaa 

This comes from the side effect of #86.
But your proposal seems to be reasonable.
I reverted the changes made from #86.
