### ISSUE TITLE
bpy.data completion missing

### ISSUE THREAD

**Issue by dreisicht** [nutti/fake-bpy-module#17]
**System Information**
  
* OS: Windows 10
* Blender version: 2.8

**Expected behavior**  
Bpy.data. gets autocompletion with objects, collections, scenes etc.

**Description about the bug**  
bpy.data. gets no further autocompletion.

**Comment by nutti** [comment]
@dreisicht 

Thanks. This issue is because of missing of the type inference.
I'm tackling to add type to the fake modules.

**Comment by nutti** [comment]
This feature is realized by type annotation now.
So, I will close this issue.

The newest pip package will be distributed after resolving other issues.
