### ISSUE TITLE
Switch to Ruff for CI

### ISSUE THREAD

**Issue by JonathanPlasse** [nutti/fake-bpy-module#171]
### Description about the feature

Currently, this project use Pylint and Pycodestyle and does not seem to use any formatter.
I propose to use Ruff to replace them and also use Ruff to format the project.
It would also run faster.

### Are you willing to contribute about this feature. (Yes/No)

Yes

**Comment by nutti** [comment]
@JonathanPlasse 

I think Ruff does not all formatting rules of Pylint and Pycodestyle.
To support Pylint and Pycodestyle users, lint test with multiple linter tool is prefer.

**Comment by JonathanPlasse** [comment]
Currently, the generated code is not linted by Pylint.
Why should the pyi files pass Pylint?
Typeshed only use black and flake8-pyi to lint and format pyi files.

In my opinion, automatically generated code should be formatted and pass flake8-pyi and nothing else.
Other linters could and should ignore the generated code.

Also, pycodestyle is totally implemented in Ruff and most important Pylint rules are implemented (cf. [How does Ruff's linter compare to Pylint?](https://docs.astral.sh/ruff/faq/#how-does-ruffs-linter-compare-to-pylint) and couple with a type checker like Pyright it pretty much cover all rules.

Finally, Ruff is fast so it can run in the editor without latency and it can auto-fix rule violations which is awesome.

**Comment by nutti** [comment]
Actually, Pylint/pycodestyle is mainly used for checking the generation code under the `src` directory.
We don't need to speed up the lint against these files [as you can see](https://github.com/nutti/fake-bpy-module/actions/runs/7356332768).

But generated code is not in the same situation compared to the generation code.
You can ignore the generated code from Pylint/pycodestyle check because we switched YAPF to Ruff.

**Comment by nutti** [comment]
@JonathanPlasse 

Is there any update?

**Comment by JonathanPlasse** [comment]
Should I go ahead adding Ruff?

**Comment by nutti** [comment]
Adding Ruff is possible as a linter.
But please do not delete the test of pylint and pycodestyle.

**Comment by nutti** [comment]
@JonathanPlasse 

Large refactoring is finished recently.
You can work this with much more safely now.

**Comment by JonathanPlasse** [comment]
> @JonathanPlasse
> 
> I think Ruff does not all formatting rules of Pylint and Pycodestyle. To support Pylint and Pycodestyle users, lint test with multiple linter tool is prefer.

@nutti, The Ruff linter that indeed do not have all formatting rules of Pylint and Pycodestyle, but with the Ruff formatter fix all these formatting rules.

I would like to at least add the Ruff formatter to format automatically the code and avoid having to manually format the code.
We can use `# fmt: skip` to avoid auto formatting some code like the list of Blender version.
![Screenshot from 2024-05-19 10-48-44](https://github.com/nutti/fake-bpy-module/assets/13716151/74d49168-304d-4729-9c3f-6958bb13653e)

**Comment by nutti** [comment]
@JonathanPlasse 

Yes, go ahead.
BTW, why does these list codes need `#fmt: skip`?
What is the proposal from ruff?

**Comment by JonathanPlasse** [comment]
It would format like this
![Screenshot from 2024-05-19 13-56-12](https://github.com/nutti/fake-bpy-module/assets/13716151/f7713b3a-e2fb-401a-b912-8ca51c790946)

**Comment by nutti** [comment]
@JonathanPlasse 

Thank you for sharing.
I think current format with `#fmt: skip` is much better.
You can add it where you think better :)

**Comment by nutti** [comment]
Ruff linter is now enabled for CI.

**Comment by JonathanPlasse** [comment]
Awesome
