### ISSUE TITLE
Missing doc strings and default argument values for addon_utils module

### ISSUE THREAD

**Issue by Andrej730** [nutti/fake-bpy-module#174]
`addon_utils` module installed with `fake-bpy-module`:
![image](https://github.com/nutti/fake-bpy-module/assets/9417531/3f4f332f-15e9-45db-91e8-1f3706da1da6)

Actual `addon_utils` (has doc strings for some methods and has default values for some arguments):
![image](https://github.com/nutti/fake-bpy-module/assets/9417531/dbff348e-a753-4c7a-8a87-90c6057b7961)

**Comment by nutti** [comment]
This issue is fixed now.

Some descriptions are still missing due to the rst parsing difficulty.
But we will close this issue for now.
