### ISSUE TITLE
bpy.ops not autocomplete

### ISSUE THREAD

**Issue by Zju-George** [nutti/fake-bpy-module#18]
**System Information**
  
* OS: [e.g. Windows]
* Blender version: [e.g. 2.79]

**Expected behavior**  
*The behavior you expect about the feature you reported.*

**Description about the bug**  
*The description about the bug.*
after pip install ....2.79, there is no bpy.ops autocomplete

**Screenshots/Files** [Optional]  
*It is good to solve the bug if you attach the screenshots or .blend file.*

**Additional comments** [Optional]

**Comment by nutti** [comment]
Nice catch!

I found that there is no files about ops and app and etc...
I think there is a bug in generation script.
I will investigate this bug later. Thanks.

**Comment by nutti** [comment]
This bug is fixed and fixed patch is now in master branch.
