### ISSUE TITLE
override_context parameter of bpy.ops.* functions is not fully typed

### ISSUE THREAD

**Issue by arcusmaximus** [nutti/fake-bpy-module#180]
* OS: Windows
* Blender version: 4.0
* fake-bpy-module-4.0 20231118

Calling any function in bpy.ops gives me a type error with VS Code's Pyright in `strict` mode. The reason is that the `override_context` parameter is typed as `typing.Optional[typing.Union[typing.Dict, 'bpy.types.Context']]` with the `typing.Dict` missing its generic parameters. Extending it to `typing.Dict[str, typing.Any]` would solve the error.

![image](https://github.com/nutti/fake-bpy-module/assets/133129/56a0649b-4a85-4121-ade2-360d8160d58b)

The same goes for the return values of bmesh.ops.*

**Comment by nutti** [comment]
This issue is fixed.

> The same goes for the return values of bmesh.ops.*

This is wrong.
bmesh.ops* does not accept override related parameters.

**Comment by arcusmaximus** [comment]
I mean the return types of bmesh.ops.*, not the parameters. For example, `bmesh.ops.create_uvsphere()` is declared with a return type of `Dict` without further details.

**Comment by nutti** [comment]
@arcusmaximus 

I misunderstood your report.
The other issue is also fixed now.
