### ISSUE TITLE
Spurious unions with typing.Any

### ISSUE THREAD

**Issue by Road-hog123** [nutti/fake-bpy-module#181]
### System Information

* OS: Windows 10
* fake_bpy_modules_4.0-20231118

### Expected behavior

The `name` attribute of an `Object` should be typed as a `str`.

### Description about the bug

`Object` inherits from `ID`, whose `name` attribute is typed as `Union[str, typing.Any]`; on closer inspection this is pervasive throughout `types.py` for boolean, string and enum type annotations.

**Comment by nutti** [comment]
This issue is fixed now.
