### ISSUE TITLE
Matrix.Rotation is not generated as a classmethod

### ISSUE THREAD

**Issue by JonathanPlasse** [nutti/fake-bpy-module#192]
### Expected behavior

[Matrix.Rotation](https://docs.blender.org/api/3.6/mathutils.html#mathutils.Matrix.Rotation) should be generated as a class method but is currently generated as a normal method (testing on commit 890e48724e5fb008bd8154589947df04535659f9 for Blender 3.6)

### Description about the bug

The .pyi look like this
```python
class Matrix:
    def Rotation(
        self,
        angle: float,
        size: int,
        axis: typing.Union["Vector", str, typing.Sequence[float]],
    ) -> "Matrix": ...
```
It should look like this
```python
class Matrix:
    @classmethod
    def Rotation(
        cls,
        angle: float,
        size: int,
        axis: typing.Union["Vector", str, typing.Sequence[float]],
    ) -> "Matrix": ...
```

**Comment by nutti** [comment]
This issue seems invalid for the current version.
