### ISSUE TITLE
Fix bpy.app.timers types

### ISSUE THREAD

**Issue by JonathanPlasse** [nutti/fake-bpy-module#196]
### Expected behavior

`bpy.app.timers.register`, `bpy.app.timers.unregister`, `bpy.app.timers.is_registered` function argument type should be `Callable[[], float]`.

**Comment by nutti** [comment]
This issue is fixed now.

**Comment by Andrej730** [comment]
@nutti 

There are still issues with this. The correct signature for the functions is `Callable[[], Union[float, None]]` as it does allow `None` return value.

I've submitted a PR to Blender to fix this issue upstream - https://projects.blender.org/blender/blender/pulls/125052, so fake-bpy could just parse the correct signatures.

![image](https://github.com/user-attachments/assets/a0914b24-c3ef-49ad-a8e2-042348065547)

**Comment by nutti** [comment]
@Andrej730 
Thanks.
But unfortunately it is difficult to parse the old style typing.
Instead, we tweaked the mod file for now.
