### ISSUE TITLE
missing descriptions from bpy_types.py

### ISSUE THREAD

**Issue by Andrej730** [nutti/fake-bpy-module#197]
Some IDs properties are defined not in C but in bpy_types.py (e.g. `Object.users_collections`) and their descriptions are missing.

`Object.users_collections` in bpy_types.py:
![image](https://github.com/nutti/fake-bpy-module/assets/9417531/89245dc7-5196-453e-8b5a-b5528167f9f8)

`Object.users_collections` in `__init__.pyi`:
![image](https://github.com/nutti/fake-bpy-module/assets/9417531/6aff9480-04f9-4e24-af03-805362c8105b)

**Comment by nutti** [comment]
Due to the generation complexity, we will not support to merge external modules into internal modules.
Also, we should handle these classes separately to keep the real structure.

If any good solution about this issue, please ping me again.
