### ISSUE TITLE
bpy.props.EnumProperty.default should be able to accept an int

### ISSUE THREAD

**Issue by mikeyX101** [nutti/fake-bpy-module#198]
### System Information

* OS: Fedora 39
* Blender version: 3.6.10 LTS

### Expected behavior

It is expected for `EnumProperty.default` to accept an `int` as an index to point to the enum entry to have by default.

### Description about the bug

EnumProperty is currently defined as `default: str | set | None`, but should also accept an `int`: `default: str | set | int | None`

### Screenshots/Files [Optional]

![image](https://github.com/nutti/fake-bpy-module/assets/67592217/10100754-5166-4c5e-8cab-b93dd81bf04b)

**Comment by nutti** [comment]
This issue is fixed now.
