### ISSUE TITLE
__init__ functions are not generated

### ISSUE THREAD

**Issue by cmbasnett** [nutti/fake-bpy-module#2]
Using the `2.79` files on the repository, and I still get errors when constructing basic objects like `Vectors` and `Quaternions` in PyCharm. It complains of unexpected arguments.

![image](https://user-images.githubusercontent.com/5035660/35478523-86faba6a-0394-11e8-8a2f-0d65bf9beb0f.png)

After looking at the generated files, the cause is obvious: no `__init__` functions are being generated for any types.

**Comment by nutti** [comment]
sorry, I didn't notice that this issue is raised.
And thanks for your bug report.

I fixed this bug and have already pushed in repository.
