### ISSUE TITLE
Matrix.decompose has incorrect return value

### ISSUE THREAD

**Issue by cmbasnett** [nutti/fake-bpy-module#200]
### System Information

* OS: Windows
* Blender version: 4.1

### Expected behavior

`Matrix.decompose` return value should be `(Vector, Quaternion, Vector)`.

### Description about the bug

```
    def decompose(self) -> 'Quaternion':
        ''' Return the translation, rotation, and scale components of this matrix.

        :rtype: 'Quaternion'
        :return: tuple of translation, rotation, and scale
        '''
        ...
```

### Screenshots/Files [Optional]

![image](https://github.com/nutti/fake-bpy-module/assets/5035660/b0ae5cb5-efcd-4000-bdec-58d2dd8bc7c5)

**Comment by nutti** [comment]
This issue is fixed.
