### ISSUE TITLE
Missing `is_registered` attribute on Operators and Panels

### ISSUE THREAD

**Issue by Andrej730** [nutti/fake-bpy-module#201]
All operators and panels seems to be missing `is_registered` attribute:
![image](https://github.com/nutti/fake-bpy-module/assets/9417531/abe42cab-bd79-4aaa-8502-e4759cf01c0c)

Though it is present on those classes:
![image](https://github.com/nutti/fake-bpy-module/assets/9417531/5fd272e5-4c12-46bc-8f43-a12b7c94d0f4)

**Comment by nutti** [comment]
This issue is now fixed.
