### ISSUE TITLE
Subclasses of ID does not inherit ID

### ISSUE THREAD

**Issue by JonathanPlasse** [nutti/fake-bpy-module#205]
### Description about the bug

For example:
`bpy.types.Object` does not have `bpy.types.ID` as base class. This means that `bpy.types.Object.copy()` is missing.

fake-bpy-module-latest: 20240511

**Comment by nutti** [comment]
@JonathanPlasse 

When does this issue start?
I think this issue solve #203 #204.

**Comment by JonathanPlasse** [comment]
The issue started after this version 20240315 -> 20240316

**Comment by JonathanPlasse** [comment]
- It is this commit 17b829dfa956d10671011178fde02c2c7a1d81ca

**Comment by nutti** [comment]
Thanks.
This issue is almost fixed, but we need to wait until the latest blender fixes the format issue to pass the linter test.
https://projects.blender.org/blender/blender/pulls/121688

**Comment by JonathanPlasse** [comment]
Awesome!

**Comment by nutti** [comment]
The patch is merged.
