### ISSUE TITLE
Module 'bgl' issue with vscode

### ISSUE THREAD

**Issue by isantos85** [nutti/fake-bpy-module#21]
i am using blender 2.8 to debug one script file with vscode and getting errors Module 'bgl' has no 'GL_INT' member
Module 'bgl' has no 'glGetIntegerv' member
Module 'bgl' has no 'GL_DEPTH_FUNC' member
Module 'bgl' has no 'GL_ALWAYS' member
 i got an idea from blender chat forum(python) to use fake-bpy-module to avoid import issues.I followed instruction from the git website and update into settings.json file path "python.autoComplete.extraPaths": ["C:/Python/Python36/Lib/site-packages"] and site-packages folder in having the data (chekc the link) http://prntscr.com/of5kr2.

please assist me, what i am missing

**Comment by nutti** [comment]
@isantos85 

Nice catch.
I think some definition is missing in the modules.

**Comment by YainVieyra** [comment]
Same problem here.
In my case I've found these undocumented modules.
GL_BLEND,
GL_POLYGON_SMOOTH,
GL_LINE_SMOOTH,
GL_POINTS,
GL_LINES,
GL_LINE_STRIP,
GL_TRIANGLES,
GL_TRIANGLE_FAN,
GL_POLYGON_OFFSET_FILL,
GL_DEPTH_TEST,
GL_CULL_FACE,
GL_TRUE,
GL_FALSE,
GL_FLOAT,
GL_RGBA,
glDrawArrays

Maybe reviewing all available bgl modules would be cool. Some of them got deprecated/replaced with the move to core profile 3.3

**Comment by nutti** [comment]
@isantos85 @YainVieyra 

Fixed this issue and all missing APIs in bgl module will be added in next release.
Thanks for your reports.

**Comment by YainVieyra** [comment]
That's very cool. Thanks
