### ISSUE TITLE
enum set in regex is broken

### ISSUE THREAD

**Issue by JonathanPlasse** [nutti/fake-bpy-module#211]
### Expected behavior

All parameters with `enum set in` in their description should have the type `set[str] | set[int]` as shown in the following code.
![Screenshot from 2024-05-14 20-30-40](https://github.com/nutti/fake-bpy-module/assets/13716151/721e21b9-680e-466e-b678-c65814dababd)

### Description about the bug
`bpy.ops.export_scene.fbx` parameter `object_types` should have the type `set[str] | set[int]` but it has the type `typing.Any | None`.
![Screenshot from 2024-05-14 20-31-03](https://github.com/nutti/fake-bpy-module/assets/13716151/0eb019d0-63a7-46be-935a-c62eb2b1f99e)
![Screenshot from 2024-05-14 20-14-33](https://github.com/nutti/fake-bpy-module/assets/13716151/cfd987db-a2a2-4d7a-8b6f-c79564893a68)

- also found thanks to #209

**Comment by JonathanPlasse** [comment]
I take this on.

**Comment by nutti** [comment]
Good to hear that. Thanks!!

I'm now trying to fix another issue.
If you want to tackle another issue in future, it is helpful to comment on the issue.
