### ISSUE TITLE
Enum value should only be type str not str | int

### ISSUE THREAD

**Issue by JonathanPlasse** [nutti/fake-bpy-module#213]
### Expected behavior

Enum in Blender can either be `str` or `int` but should ideally only be `str` not `int`.
The integer value is part of the internals of Blender and is not part of the documentation.
The integer value could change meaning between Blender version and thus break.
With the string value, it should happen much less often or never.
That is why it is recommended to use only string value.
I think we should reflect this in the pyi files and only accept string value for enum value.
This is inline with the idea of type checking with fake-bpy-module to make code more robust.

**Comment by nutti** [comment]
@JonathanPlasse 

I agreed this idea.
I'll check your PR from now.
