### ISSUE TITLE
String Enum type should be a union of literal instead of str

### ISSUE THREAD

**Issue by JonathanPlasse** [nutti/fake-bpy-module#216]
### Description about the feature

In Blender API, there are enum string type, currently the type used is `str | int` and ideally should only be `str` (c.f. #213).
Even better would be that the type is a union of possible literal string variant.
For example the return type of `bpy.types.Operator.execute()` is
![Screenshot from 2024-05-15 23-00-24](https://github.com/nutti/fake-bpy-module/assets/13716151/997b32ac-5307-4249-9205-3089952fded5)
The type would be `Literal["RUNNING_MODAL"] | Literal["CANCELLED"] | Literal["FINISHED"] | Literal["PASS_THROUGH"] | Literal["INTERFACE"]`.

### Are you willing to contribute about this feature. (Yes/No)

Yes

**Comment by nutti** [comment]
@JonathanPlasse 

I assigned this issue to you.
Do you have an idea about this?
I think this is difficult for our approach to realize this.

**Comment by JonathanPlasse** [comment]
If the RST contain the link to the enum page in the return type (e.g. `Operator Return Items`), it should be feasible.
Otherwise, it will be difficult.

![image](https://github.com/nutti/fake-bpy-module/assets/13716151/eabd008e-c392-419e-9b9b-20048577efcc)

**Comment by nutti** [comment]
I think it is difficult to parse other RST files while processing the document.
If you have an idea, I will remain this issue.
Or, I will close this issue.
What do you think? @JonathanPlasse

**Comment by JonathanPlasse** [comment]
I would like to take a deeper look to implement it.

**Comment by JonathanPlasse** [comment]
When encountering an rna enum reference we could parse on the fly the corresponding rst file.
![Screenshot from 2024-06-03 21-51-08](https://github.com/nutti/fake-bpy-module/assets/13716151/d7043b63-78b2-450c-ad21-a3d1396e9ae5)
![Screenshot from 2024-06-03 21-51-40](https://github.com/nutti/fake-bpy-module/assets/13716151/d9f04874-ad19-40bc-84db-1a7854b8f450)

I will see if I can make it work.

**Comment by nutti** [comment]
Thank you.
This needs to support to read related files from somewhere.

I'm wondering this should be done in transformer or analyzer phase.
https://github.com/nutti/fake-bpy-module/tree/master/src/fake_bpy_module/analyzer
https://github.com/nutti/fake-bpy-module/tree/master/src/fake_bpy_module/transformer

I think adding this feature into the transformer phase is much simpler and easy to maintenance in future.
