### ISSUE TITLE
mathutils.Matrix.LocRotScale() has no return type

### ISSUE THREAD

**Issue by Road-hog123** [nutti/fake-bpy-module#219]
I see that the return type is [prefixed with 4x4](https://docs.blender.org/api/4.1/mathutils.html#mathutils.Matrix.LocRotScale) and that there is a special case for this in the code, but it doesn't appear to have worked.
https://github.com/nutti/fake-bpy-module/blob/045cc31b824999ebba63eec4bfc47ac9c3599ad6/src/fake_bpy_module/transformer/data_type_refiner.py#L184-L188

**Comment by nutti** [comment]
This issue is fixed now.
