### ISSUE TITLE
Operator types are not included

### ISSUE THREAD

**Issue by TzuChieh** [nutti/fake-bpy-module#22]
**System Information**
  
* OS: Windows 7
* Blender version: 2.80

**Expected behavior**  
For example, `bpy.types` should have a `TOPBAR_MT_file_export` attribute.

**Description about the bug**  
`bpy.types` do not have a `TOPBAR_MT_file_export` attribute.

**Comment by nutti** [comment]
@TzuChieh 

Thanks.
`TOPBAR_MT_file_export` is not included in fake-bpy-module now because this class defined at python scripts.
But I think it is good for us to complete all classes.

**Comment by nutti** [comment]
Fixed this feature and new release has all APIs.

**Comment by SK83RJOSH** [comment]
@nutti are you sure this is fixed? I'm doing extension development for 2.82 and using your pip package -- there's no `TOPBAR_MT_file_export` and some linting errors with things like:

`bpy.types.TOPBAR_MT_file_export.remove(export)`
`Module 'bpy.types' has no 'TOPBAR_MT_file_export' memberpylint(no-member)`

`bpy.types.Scene.property = bpy.props.PointerProperty(type=CustomProperty)`
`Assigning result of a function call, where the function has no returnpylint(assignment-from-no-return)`

**Comment by SK83RJOSH** [comment]
Seems likely, yeah! Surprised I didn't come across that issue when searching issues, sorry about that. I am curious about the return types of properties and so on though. Shouldn't those be annotated as classes or with return types? :)

**Comment by nutti** [comment]
@SK83RJOSH 

> the return types of properties and so on

Exactly.
Do you know what type should we return type?
There are no information of return type about **Property in [docs](https://docs.blender.org/api/current/bpy.props.html).
