### ISSUE TITLE
4.1 not available on pypi

### ISSUE THREAD

**Issue by walles** [nutti/fake-bpy-module#227]
### Expected behavior

`pip3 install fake-bpy-module-4.1` should install `fake-bpy-module-4.1`.

### Description about the bug

```
(env) ~ $ pip3 install fake-bpy-module-4.1
ERROR: Could not find a version that satisfies the requirement fake-bpy-module-4.1 (from versions: none)
ERROR: No matching distribution found for fake-bpy-module-4.1
(env) ~ [0|1]$ 
```

### Notes

`README.md` says 4.1 should be available, but the link doesn't work:
https://github.com/nutti/fake-bpy-module/blob/6400d1c064c3526735361ebbe2ce6f7a39c67e92/README.md?plain=1#L89

**Comment by JonathanPlasse** [comment]
> When do you expect fake-bpy-module-4.1 to be published on PyPI?

> Before releasing new version, we consider to fix all current issues.

- https://github.com/nutti/fake-bpy-module/pull/206#issuecomment-2110173403

**Comment by walles** [comment]
What confused me is that `README.md` says 4.1 is already available, even though that seems not to be the case:
https://github.com/nutti/fake-bpy-module/blob/6400d1c064c3526735361ebbe2ce6f7a39c67e92/README.md?plain=1#L89

**Comment by nutti** [comment]
We will release new version after resolving issue 234.
Other issues are complex to solve.

**Comment by nutti** [comment]
fake-bpy-module-4.1 is released now.
Thank you contributors!

**Comment by JonathanPlasse** [comment]
https://pypi.org/project/fake-bpy-module-4.1/
