### ISSUE TITLE
LayerObjects.active can be None

### ISSUE THREAD

**Issue by Andrej730** [nutti/fake-bpy-module#228]
fake-bpy-module-latest==20240522

See example below, type checker complains though it is possible to assign None to `active` attribute (or get `None` from it), so `active` should have a type `typing.Optional[Object]` instead of `Object`.

```python
import bpy

# Cannot assign to attribute "active" for class "LayerObjects"
#   "None" is incompatible with "Object"
bpy.context.view_layer.objects.active = None
```

![image](https://github.com/nutti/fake-bpy-module/assets/9417531/b5d9dd9a-253d-4b18-8b28-83d08618f604)

**Comment by nutti** [comment]
This issue is now fixed.
