### ISSUE TITLE
Wrong type hinting for bpy.props.EnumProperty

### ISSUE THREAD

**Issue by TzuChieh** [nutti/fake-bpy-module#23]
**System Information**
  
* OS: Windows 7
* Blender version: 2.80

**Expected behavior**  
The `items` keyword argument of `bpy.props.EnumProperty` should be tuples.

**Description about the bug**  
Currently it is defined as `items: str`.

**Comment by nutti** [comment]
@TzuChieh 

Thanks. You're right.
But I found the commit https://github.com/nutti/fake-bpy-module/commit/d20de984bb06781ba3d0ee4ea807fc54ee351775 already fixes this issue.
This issue will be disappeared in next release.
