### ISSUE TITLE
Operator.poll_message_set regression

### ISSUE THREAD

**Issue by Andrej730** [nutti/fake-bpy-module#231]
fake-bpy-module-latest==20240522

```python

import bpy

class InspectFromObject(bpy.types.Operator):
    @classmethod
    def poll(cls, context):
        # Argument missing for parameter "args"
        cls.poll_message_set("Test")
        return False
```

Not sure when this issue occurred but it seems it wasn't present in #133 
1) `poll_message_set` is expecting some other argument `args` and it's not optional (no idea what `args` is for here though)

2) `args` argument is a single argument but it actually represent variable number of position arguments, see [Blender docs](https://docs.blender.org/api/current/bpy.types.Operator.html#bpy.types.Operator.poll_message_set).

![image](https://github.com/nutti/fake-bpy-module/assets/9417531/d9f8aeeb-5fa0-46ad-b797-d33055d1fa75)

![image](https://github.com/nutti/fake-bpy-module/assets/9417531/bad3b205-c4c3-4347-a484-965d2afac720)

**Comment by nutti** [comment]
This issue is now fixed.
