### ISSUE TITLE
BlendData getitem returns wrong type

### ISSUE THREAD

**Issue by Andrej730** [nutti/fake-bpy-module#234]
Example for `BlendDataObjects `(same for the other BlendData types):
```python
from typing import assert_type
import bpy
obj = bpy.data.objects["Cube"]
# "assert_type" mismatch: expected "Object" but received "Any"
assert_type(obj, bpy.types.Object)
```

I assume it happens because `BlendData` inherit from two classes - `bpy_struct` and `bpy_props_collection[Object]`.

![image](https://github.com/nutti/fake-bpy-module/assets/9417531/03e86e02-f22b-4df3-87e1-48508152f348)

Though `bpy_props_collection[Object].__getitem__` should cover this case:
![image](https://github.com/nutti/fake-bpy-module/assets/9417531/4c43f5d4-2c31-4654-bce5-e7af9bed3e4b)

`bpy_struct` also has `__getitem__` implemented and it overrides the `bpy_props_collection` method:
![image](https://github.com/nutti/fake-bpy-module/assets/9417531/a6c3b372-e190-4b00-8472-2e8fed2709d2)

**Comment by nutti** [comment]
@Andrej730 
Is `__getitem__` not needed for `bpy_struct`?

**Comment by nutti** [comment]
@Andrej730 

If not needed, you can modify below file directly to fix this issue.
https://github.com/nutti/fake-bpy-module/blob/1527d132e8e79974644ccac400d33fbb1d56dcf5/src/mods/common/analyzer/append/bpy.types.mod.rst?plain=1#L82

**Comment by nutti** [comment]
@Road-hog123 

Can this issue solve by deleting `__getitem__` from `bpy_struct`?

**Comment by Andrej730** [comment]
`bpy_struct` has `__getitem__` in the actual `bpy`, so I guess removing it indeed could lead to issues (can't pinpoint any specific though).

```python
bpy.types.bpy_struct.__getitem__
# <slot wrapper '__getitem__' of 'bpy_struct' objects>

bpy.types.BlendDataObjects.__getitem__
# <slot wrapper '__getitem__' of 'bpy_struct' objects>
```

**Comment by nutti** [comment]
@Road-hog123 @Andrej730 

It is difficult to search the complete solution because of Blender internal tweaks.
I think removing `__getitem__` from `bpy_struct` makes better user experiences.
What do you think?

**Comment by Andrej730** [comment]
> I think removing `__getitem__` from `bpy_struct` makes better user experiences.

We can try since this one is easy to revert either way if we'll find some edge case for this.

**Comment by Road-hog123** [comment]
@nutti

Unless all methods are removed from `bpy_struct` it will continue to override or incorrectly add methods when collections inherit from it (`bpy.data.objects` receives `get()` and `pop()` from `bpy_struct` when it should only receive `get()` from `bpy_prop_collection`).

**Comment by nutti** [comment]
@Road-hog123 

Ah, I could understand your idea.
Should we reverse inheritance order like this?

* Current

```python
class BlendDataObjects(bpy_struct, bpy_prop_collection[Object]):
```

* Better one

```python
class BlendDataObjects(bpy_prop_collection[Object], bpy_struct):
```

**Comment by Road-hog123** [comment]
> Should we reverse inheritance order like this?
> ```python
> class BlendDataObjects(bpy_prop_collection[Object], bpy_struct):
> ```

@nutti That's what I tried to suggest [yesterday](#issuecomment-2135271460)—it would fix most issues (inheriting from subscripted classes before plain classes (`a[b], c`) seems like a good idea in general).

The only part this won't fix is autocomplete for non-existent attributes like `bpy.data.objects.pop()`, which can only be fixed by not inheriting from `bpy_struct` at all.

**Comment by nutti** [comment]
This issue is now fixed.
