### ISSUE TITLE
bpy_prop_collection is missing __contains__

### ISSUE THREAD

**Issue by Andrej730** [nutti/fake-bpy-module#235]
See example below. [__contains__ implementation in bpy_rna.cc](https://projects.blender.org/blender/blender/src/commit/7911e2614fa2bc17420a99f4e4d8e6a3346fa9ba/source/blender/python/intern/bpy_rna.cc#L3377-L3406) for a reference.

```python
import bpy

obj = bpy.data.objects["Cube"]
assert isinstance(obj, bpy.types.Object)
# Operator "in" not supported for types "str" and "LayerObjects"
print(obj.name in bpy.context.view_layer.objects)

0 in bpy.context.view_layer.objects
# note that it says that is supports only a string or a tuple of string
# TypeError: bpy_prop_collection.__contains__: expected a string or a tuple of strings

('test', 'test') in bpy.context.view_layer.objects
# but tuple of strings is only valid argument for BlendData collections
#KeyError: '(id, lib) in bpy_prop_collection: is only valid for bpy.data collections, not ViewLayer'

```

**Comment by nutti** [comment]
@Andrej730 
Hi, thank you for launching many issues!
Please tell me the exact specification about `__contains__`.

BTW, This is an easy issue. If you want to contribute this, you can fix by modifying the .mod file.
https://github.com/nutti/fake-bpy-module/blob/1527d132e8e79974644ccac400d33fbb1d56dcf5/src/mods/common/analyzer/append/bpy.types.mod.rst?plain=1#L31

**Comment by nutti** [comment]
Distinguishing internal specification is out of this module scope.
Only adding `__contains__` to `bpy_prop_collection` is feasible.

**Comment by nutti** [comment]
Patch is now merged.

**Comment by Andrej730** [comment]
For all `bpy_prop_collection` key can only be a `str`. But for all BlendData types it can also be `str | tuple[str, str | None]`.

Is there a way to specify `__contains__` for all BlendData classes?

**Comment by nutti** [comment]
@Andrej730 

I think this is difficult because our generation code does not see any internal C code.
If you have any idea, please let us know.
