### ISSUE TITLE
Enums should be considered as String instead of Int in Python

### ISSUE THREAD

**Issue by EmileSonneveld** [nutti/fake-bpy-module#24]
**System Information**
  
* OS: Windows
* Blender version: 2.79 (Python version 3.6 used in IDE)
* IDE: PyCharm

**Expected behavior**  
in types.py (Downloaded from the README)
```def report(self, type: typing.Set[int], message: str):```
Should be:
```def report(self, type: typing.Set[str], message: str):```
As enums are exposed as strings in Python. If this seems non-intuitive, `typing.Set[object]` could also be used, to ignore the problem

There are many more cases of this issue. It would be very nice to be fixed :)

**Comment by nutti** [comment]
@EmileSonneveld 

Thanks.

> As enums are exposed as strings in Python.

You are right. enum must be string in Python.
But I'm not sure all enums in Python are string.
Do you know any exceptions about this rule? (ex. enums -> int)

**Comment by EmileSonneveld** [comment]
I don't program python a lot, but I have seen cases in other languages where enums are indeed implemented as ints. 

I use this tool mostly to browse faster trough the Blender API. (Thanks for that! 😃)
So for my use case, the type of enums can be 'object' without problems. Or otherwise perhaps, `typing.Union[int, str]` https://docs.python.org/3/library/typing.html#typing.Union

**Comment by nutti** [comment]
> Or otherwise perhaps, typing.Union[int, str]

Nice suggestion. Thanks!
I will use this feature to fix this issue.

**Comment by nutti** [comment]
Fixed this issue.
Enum will be considered as `str` or `int` in newer version.

@EmileSonneveld 

Thanks for your suggestion and bug reports
