### ISSUE TITLE
set() converted to None()

### ISSUE THREAD

**Issue by Road-hog123** [nutti/fake-bpy-module#244]
`override` and `tags` parameters of functions in `bpy.props` (except `RemoveProperty`) default to `set()` and are typed `set` in the RST, however in the generated module they default to `None()` (`None` is not callable) and are typed `set | None`.

This is also true for `bpy_struct.keyframe_insert()`'s `options` parameter, although it is presently untyped in the RST due to a typo: [#122734 - PyAPI Doc: fix typos causing untyped parameters](https://projects.blender.org/blender/blender/pulls/122734).

**Comment by nutti** [comment]
This is now fixed.
