### ISSUE TITLE
BMEdgeSeq.new() verts parameter untyped

### ISSUE THREAD

**Issue by Road-hog123** [nutti/fake-bpy-module#245]
[`BMEdgeSeq.new()`](https://docs.blender.org/api/main/bmesh.types.html#bmesh.types.BMEdgeSeq.new)'s `verts` parameter is typed as "pair of `BMVert`" in the RST, but "pair of `x`" is not interpreted as "sequence of `x`" by the generation code—should this be handled in the generation code, or should I change the documentation to use the word "sequence"?

**Comment by nutti** [comment]
Changing the documentation is not good for this case.
In my understanding, `BMEdgeSeq.new()` accepts two elements of array.
So, we need to add a logic to data type refiner.

https://github.com/nutti/fake-bpy-module/blob/master/src/fake_bpy_module/transformer/data_type_refiner.py

Are you willing to do this?

You can refer the similar code in the `DataTypeRefiner._get_refined_data_type_fast` method.
https://github.com/nutti/fake-bpy-module/blob/master/src/fake_bpy_module/transformer/data_type_refiner.py#L137

**Comment by nutti** [comment]
This issue is now fixed.
