### ISSUE TITLE
The generated file launch.py has a string bug.

### ISSUE THREAD

**Issue by lxq** [nutti/fake-bpy-module#25]
**System Information**
  Windows 10 x64
* OS: [e.g. Windows]
* Blender version: [e.g. 2.79]
2.79

**Expected behavior**  
*The behavior you expect about the feature you reported.*
It will start Blender failed.

**Description about the bug**  
*The description about the bug.*
File launch.py generated by fake-pyb-module has a bug of a string. The original code looks like:
editor_address=**f**"http://localhost:{os.environ['EDITOR_PORT']}",

It must delete 'f'.

**Screenshots/Files** [Optional]  
*It is good to solve the bug if you attach the screenshots or .blend file.*

**Additional comments** [Optional]

**Comment by nutti** [comment]
@lxq 

The file `launch.py` is not a part of fake-bpy-module.
So, I think it is not a problem of fake-bpy-module.
Please check your environment again.

**Comment by nutti** [comment]
@lxq 

This issue is not seems to be related to this project, so I close this issue for now.
Feel free to reopen if there are any problems.
