### ISSUE TITLE
Missing bl_rna attribute

### ISSUE THREAD

**Issue by Andrej730** [nutti/fake-bpy-module#255]
fake-bpy-module-latest==20240618

Example is below.
Mainly I use `.bl_rna` for properties - to access the properties names and default values.
That's probably too low level to be fixed but wanted to document it here either way.

```python
import bpy

obj = bpy.data.objects["Test"]
# Cannot access attribute "bl_rna" for class "Object"
#   Attribute "bl_rna" is unknown
print(obj.bl_rna.properties['location'].name)
```

**Comment by nutti** [comment]
Patch is now merged.
