### ISSUE TITLE
Wrong typing for bl_options

### ISSUE THREAD

**Issue by Andrej730** [nutti/fake-bpy-module#256]
fake-bpy-module-latest==20240618

In current version it allows any values.
![image](https://github.com/nutti/fake-bpy-module/assets/9417531/b755209e-ff99-4c07-8703-54d40eac1c21)

Though Blender [specifies it](https://docs.blender.org/api/current/bpy.types.Operator.html#bpy.types.Operator.bl_options) as "enum set", so it should be `set[str]` atleast.
![image](https://github.com/nutti/fake-bpy-module/assets/9417531/61508912-4bb6-4a8c-b178-3c0878f0bf15)

It would be nice if it could be typed as a set of specific literals from [Operator Type Flags](https://docs.blender.org/api/current/bpy_types_enum_items/operator_type_flag_items.html#rna-enum-operator-type-flag-items).

That would give us a warning for wrong values and there would be a tooltip with supported values.
![image](https://github.com/nutti/fake-bpy-module/assets/9417531/bd104c82-4466-48b1-b36a-e6dde54d1bbb)
Similar suggestion for other types with bl_options:
- bpy.types.Panel - https://docs.blender.org/api/current/bpy.types.Panel.html#bpy.types.Panel.bl_options
- bpy.types.AssetShelf - https://docs.blender.org/api/current/bpy.types.AssetShelf.html#bpy.types.AssetShelf.bl_options
- bpy.types.GizmoGroup - https://docs.blender.org/api/current/bpy.types.GizmoGroup.html#bpy.types.GizmoGroup.bl_options
- bpy.types.KeyingSetInfo (also has the same bug as Operator - allows `typing.Any`) - https://docs.blender.org/api/current/bpy.types.KeyingSetInfo.html#bpy.types.KeyingSetInfo.bl_options
- bpy.types.Macro (also has the same bug as Operator - allows `typing.Any`) - https://docs.blender.org/api/current/bpy.types.Macro.html#bpy.types.Macro.bl_options
- bpy.types.Menu - https://docs.blender.org/api/current/bpy.types.Menu.html#bpy.types.Menu.bl_options

Note that there are also default values for `bl_options`. E.g. for Operator it's `{"DEFAULT"}`.

Snippet:
```python
import bpy
from typing import Literal


class FakeOperator:
    bl_options: set[
        Literal[
            "REGISTER",
            "UNDO",
            "UNDO_GROUPED",
            "BLOCKING",
            "MACRO",
            "GRAB_CURSOR",
            "GRAB_CURSOR_X",
            "GRAB_CURSOR_Y",
            "DEPENDS_ON_CURSOR",
            "PRESET",
            "INTERNAL",
        ]
    ]


class NewOperator(FakeOperator):
    bl_options = {"REGISTER", "UNDO", "WRONG_VALUE", ""}
    bl_idname = "Test"


class Operator(bpy.types.Operator):
    bl_options = {"REGISTER", "UNDO", "WRONG_VALUE", ""}
    bl_idname = "Test"
```

**Comment by nutti** [comment]
Fix this issue.
Complete solution with `Literal` annotation should be supported by #216 .
