### ISSUE TITLE
foreach_get and foreach_set doesn't support numpy buffers

### ISSUE THREAD

**Issue by Andrej730** [nutti/fake-bpy-module#257]
fake-bpy-module-latest==20240618

`foreach_get` and `foreach_set` [allow very optimized way to copy data between buffers](https://b3d.interplanety.org/en/optimizing-the-speed-of-data-access-using-foreach_/) but it only works with the types that support buffer protocol and it's probably way to use those methods - for that purpose I typically would use numpy array but it seems to be incompatible with the current typing for those methods. 
It's also possible that people would use `array.array` but haven't seen anyone using it in practice - mostly it's numpy arrays.

```python
import bpy
import numpy as np

mesh = bpy.data.meshes["Test"]
buffer = np.empty(len(mesh.polygons), dtype=np.int32)

# Argument of type "NDArray[signedinteger[_32Bit]]" cannot be assigned to parameter "seq" of type "MutableSequence[bool] | MutableSequence[int] | MutableSequence[float]" in function "foreach_get"
#   Type "NDArray[signedinteger[_32Bit]]" is incompatible with type "MutableSequence[bool] | MutableSequence[int] | MutableSequence[float]"
#     "ndarray[Any, dtype[signedinteger[_32Bit]]]" is incompatible with "MutableSequence[bool]"
#     "ndarray[Any, dtype[signedinteger[_32Bit]]]" is incompatible with "MutableSequence[int]"
#     "ndarray[Any, dtype[signedinteger[_32Bit]]]" is incompatible with "MutableSequence[float]"

mesh.polygons.foreach_get("material_index", buffer)
mesh.polygons.foreach_set("material_index", buffer)
```

**Comment by nutti** [comment]
This relates to #184.

@Road-hog123 @JonathanPlasse 
Do you have any good solution about this?
If it is difficult to solve this, I will mark this issue as "won't fix".
