### ISSUE TITLE
Feature request - more specific types for obj.data

### ISSUE THREAD

**Issue by Andrej730** [nutti/fake-bpy-module#258]
Current `bpy.types.Object.data` has a type `bpy.types.ID` which doesn't get narrowed if you're trying to handle different cases for current objects data and always stays `bpy.types.ID` (example is below). Also `bpy.types.ID` includes many more types than actually can be used in `obj.data`.

The proposal is to replace it's type with a union with [actually possible data types](https://docs.blender.org/api/current/bpy_types_enum_items/object_type_items.html) or some alias for that union like `ObjectData` so we could use this alias in the code.

```python
import bpy

obj = bpy.context.active_object
assert obj
data = obj.data
# Currently: Type of "data" is "ID | None"
# Feature request:
# Type of "data" is "ObjectData"
# or Union[bpy.types.Mesh, bpy.types.Curve, bpy.types.Light, etc...]
reveal_type(data)

assert data

if isinstance(data, bpy.types.Mesh):
    # mesh logic
    pass
elif data is None:
    # empty logic
    pass
elif isinstance(data, bpy.types.Curve):
    # curve logic
    pass
else:
    # Currently: Type of "data" is "ID"
    # Feature request:
    # Type of "data" is Union[bpy.types.Light, bpy.types.Volume, bpy.types.Armature, etc...]
    reveal_type(data)
```

**Comment by Road-hog123** [comment]
`ID` is the type specified for this attribute [in the documentation](https://docs.blender.org/api/current/bpy.types.Object.html#bpy.types.Object.data).

Unfortunately the linked page defines the literal string values for `Object.type` (#216), not the Python types for `Object.data`—if you're able to compile an exhaustive list of possible types, it would significantly aid us in contributing back to Blender's documentation or overriding the type in this module. 👍

**Comment by Andrej730** [comment]
> if you're able to compile an exhaustive list of possible types

Here it is except the "GREASEPENCIL" - couldn't reproduce it. In docs they say it's "Grease Pencil v3." so maybe it will have it own type in the future when gp3 will be released.
```
test = {
    "MESH": bpy.types.Mesh,
    "CURVE": bpy.types.Curve,
    "SURFACE": bpy.types.SurfaceCurve,
    "META": bpy.types.MetaBall,
    "FONT": bpy.types.TextCurve,
    "CURVES": bpy.types.Curves,
    "POINTCLOUD": bpy.types.PointCloud,
    "VOLUME": bpy.types.Volume,
    "GPENCIL": bpy.types.GreasePencil,
    "GREASEPENCIL": ...,
    "ARMATURE": bpy.types.Armature,
    "LATTICE": bpy.types.Lattice,
    "EMPTY": None,
    "LIGHT": bpy.types.Light,
    "LIGHT_PROBE": bpy.types.LightProbe,
    "CAMERA": bpy.types.Camera,
    "SPEAKER": bpy.types.Speaker,
}
```

**Comment by Road-hog123** [comment]
Looks like `GREASEPENCIL` is only in 4.3 alpha, and has type `bpy.types.GreasePencilv3`.

**Comment by Andrej730** [comment]
> Looks like `GREASEPENCIL` is only in 4.3 alpha, and has type `bpy.types.GreasePencilv3`.

Updated the post. `GreasePencilv3` sounds like a temporary name that might not be included in the actual release 😁

**Comment by nutti** [comment]
@Road-hog123 

I think we can also fix this by using mod file.
Should I wait you until your trial to fix the documentation?

**Comment by Road-hog123** [comment]
@nutti you can fix this with a mod file, fixing this in the Blender documentation is beyond my abilities at the moment.

**Comment by nutti** [comment]
Patch is now merged.
