### ISSUE TITLE
Default values that are instances of classes are typed as calls to None

### ISSUE THREAD

**Issue by Road-hog123** [nutti/fake-bpy-module#267]
Possibly related to #244

Various functions in `bmesh.ops` have parameters that default to instances of `mathutils` classes e.g. `bisect_plane`'s `plane_co` and `plane_no` which default to `mathutils.Vector()` and `create_circle`'s `matrix` which defaults to `mathutils.Matrix.Identity(4)`, but these get converted to `None()` and `None(4)` respectively.

**Comment by nutti** [comment]
This issue is now fixed.
