### ISSUE TITLE
Bpy Module is Completely Empty, does not Autocomplete

### ISSUE THREAD

**Issue by Gonderage** [nutti/fake-bpy-module#271]
### System Information

* OS: Fedora 39 Linux
* Blender version: 4.1

### Expected behavior

Module `bpy` shows `context`, `data`, etc.

### Description about the bug

Module `bpy` is empty in VSCode, but all other modules are autocompleting.

![Screenshot from 2024-06-24 21-14-31](https://github.com/nutti/fake-bpy-module/assets/78834252/3a15404a-8731-4154-80d8-c359235d50af)
![Screenshot from 2024-06-24 21-14-56](https://github.com/nutti/fake-bpy-module/assets/78834252/14a1758b-f430-46cb-9b53-d4f2fd0dcf37)
![Screenshot from 2024-06-24 21-14-45](https://github.com/nutti/fake-bpy-module/assets/78834252/3e49b715-dfd8-42f5-ae97-480ba47b0587)

**Comment by nutti** [comment]
This is weird.
Is bpy/__init__.pyi also empty?

**Comment by Gonderage** [comment]
No, __init__.py is not empty.

![image](https://github.com/nutti/fake-bpy-module/assets/78834252/4f7ce67a-d8cf-4628-8dd4-9a3b1bc5d6b5)

**Comment by nutti** [comment]
Then, this error should be come from the editor settings.
I suspect your file is not connected to some python project (from the name `Untitle-1`).
Please confirm that the source code which you edit, is connected to the project.

**Comment by nutti** [comment]
@Gonderage 

Any update?

**Comment by JonathanPlasse** [comment]
The generation sometimes fails and a lot of modules are missing or incomplete.
Some fake-bpy-module-latest versions with this problem can be found on PyPI.

**Comment by nutti** [comment]
@JonathanPlasse 

Thank you for the response.
Does the current one also have same issue?

**Comment by JonathanPlasse** [comment]
I haven't seen the problem recently.

**Comment by nutti** [comment]
Thank you.
OK, then I will close this issue.
Maybe this issue comes from the result of refactoring when I introduced the ruff linter.
