### ISSUE TITLE
Vector swizzles are returning typing.Any instead of Vector

### ISSUE THREAD

**Issue by Andrej730** [nutti/fake-bpy-module#272]
See example below.

```python
from mathutils import Vector
from typing import assert_type

a = Vector()
b = a.xyz
# "assert_type" mismatch: expected "Vector" but received "Any"
assert_type(b, Vector)
```

![image](https://github.com/nutti/fake-bpy-module/assets/9417531/1aecd7cf-ccbb-409e-9b0e-a3ac537186f8)

**Comment by Road-hog123** [comment]
I have submitted a PR to fix this upstream, but it probably won't get into 4.2 LTS. :(
[#124275 - PyDoc Fix: mathutils Vector swizzle attributes untyped](https://projects.blender.org/blender/blender/pulls/124275)

**Comment by nutti** [comment]
@Road-hog123 
Thank you.
If the PR is merged into the blender repository, please let me know.

**Comment by Road-hog123** [comment]
@nutti PR has been merged! 🎉

**Comment by nutti** [comment]
@Road-hog123 
Good news!
Thank you for the notification.

**Comment by nutti** [comment]
I will close this issue.
