### ISSUE TITLE
`context.active_bone` can also be `bpy.types.Bone`

### ISSUE THREAD

**Issue by Andrej730** [nutti/fake-bpy-module#273]
It's currently typed as EditBone

![image](https://github.com/nutti/fake-bpy-module/assets/9417531/b23d077a-f940-4ab9-b8a5-2c2a61fd38c3)

But it can also be just `bpy.types.Bone` (when armature not in EDIT mode).
![image](https://github.com/nutti/fake-bpy-module/assets/9417531/3827d9dc-327b-4ca1-97bb-c9c017d6c39d)

Looks like it's an issue upstream - https://docs.blender.org/api/current/bpy.context.html#bpy.context.active_bone

**Comment by nutti** [comment]
Created PR for Blender repository.
https://projects.blender.org/blender/blender/pulls/124406

**Comment by nutti** [comment]
PR is now merged.
