### ISSUE TITLE
Redundant `| None` types in the argument types

### ISSUE THREAD

**Issue by Andrej730** [nutti/fake-bpy-module#275]
On the left it's `bpy/utils/__init__.py` from fake-bpy, on the right - Blender 4.1 `bpy/utils/__init__.py`. 

Note two issues: 
1) `path` and `create` have a redundant `| None` in their types.
2) Signature is missing `*, ` making `path` and `create` not keyword-only though they actually are.

![image](https://github.com/nutti/fake-bpy-module/assets/9417531/8204d1ba-545e-4a32-8c74-c011168507fa)

**Comment by Road-hog123** [comment]
1. I guess the whole "if not Never None must accept None" should not be applied to parts of the API defined in Python files...

2. I reported a similar issue in #266.

**Comment by nutti** [comment]
Blender document is also mistake.
https://projects.blender.org/blender/blender/pulls/125316
