### ISSUE TITLE
duplicated signatures

### ISSUE THREAD

**Issue by Andrej730** [nutti/fake-bpy-module#276]
File: `bpy/utils/__init__.pyi`

`unregister_manual_map`, `unregister_tool`, `user_resource` and some other signatures appear twice.

![image](https://github.com/nutti/fake-bpy-module/assets/9417531/47223609-112b-4e8d-aeff-f5a83b8b8e47)

**Comment by Road-hog123** [comment]
I reported a similar issue in #265

**Comment by nutti** [comment]
This is duplicate of #265.
