### ISSUE TITLE
Default value `sys.float_info.max` converted to `None`

### ISSUE THREAD

**Issue by Road-hog123** [nutti/fake-bpy-module#284]
[`BVHTree.ray_cast`](https://docs.blender.org/api/current/mathutils.bvhtree.html#mathutils.bvhtree.BVHTree.ray_cast)'s `distance` argument defaults to `sys.float_info.max`, but in the generated modules this has become `None` (which is not compatible with `float`).

**Comment by Road-hog123** [comment]
[`bpy.utils.resource_path`](https://docs.blender.org/api/main/bpy.utils.html#bpy.utils.resource_path) has a similar problem—`major` defaults to `bpy.app.version[0]` and `minor` to `bpy.app.version[1]`, but in the generated modules these are `None[0]` and `None[1]` respectively (`None` is not subscriptable).

**Comment by nutti** [comment]
Duplicate of #267.
Solved by fixing it.
