### ISSUE TITLE
Some child classes copy from parent instead of inheriting

### ISSUE THREAD

**Issue by Road-hog123** [nutti/fake-bpy-module#285]
In `scripts/modules/bpy_types.py`, `Menu` is defined with a method `path_menu()` whose docstring starts `Populate a menu from a list of paths`. If you search that string in the generated modules you'll find 583 results because 582 classes that should inherit from `Menu` instead have a copy of the method.

**Comment by nutti** [comment]
Fixed this.
Classes in the external modules also copied other methods.
