### ISSUE TITLE
`UILayout.label` accepts positional arguments

### ISSUE THREAD

**Issue by Andrej730** [nutti/fake-bpy-module#293]
fake-bpy-module-latest==20240724

See the snippet below, it fails in Blender but has not typing issues - it seems `.label` needs `*` at the beginning of it's signature to mark arguments as keyword-only.

```python
import bpy
from bpy.types import Panel

class PanelTest(Panel):
    def draw(self, context):
        # In Blender it will fail with:
        # TypeError: UILayout.label(): required parameter "text" to be a keyword argument!
        self.layout.label("Selected domain:")

```

**Comment by nutti** [comment]
@Andrej730 

I think this is not only for `UILayout.label`.
https://docs.blender.org/api/current/bpy.types.UILayout.html
Should not arguments with default value accept positional arguments?

**Comment by nutti** [comment]
@Andrej730 

If there is no suggestion, I will make a PR to fix the related APIs from my knowledge.

**Comment by Andrej730** [comment]
> Should not arguments with default value accept positional arguments?

@nutti no idea, I don't have that deep knowledge how it works internally.

**Comment by nutti** [comment]
The document generation code does not have any information about positional/non-positional arguments.
So, fixed this issue by tweaking argument attributes.
