### ISSUE TITLE
`fake-bpy-module-4.2` isn't up to download

### ISSUE THREAD

**Issue by DasLixou** [nutti/fake-bpy-module#298]
`fake-bpy-module-4.2` isn't up to download on pip, the link in the README also gives a 404

**Comment by nutti** [comment]
@DasLixou 

Yes. Actually, we have not released yet for 4.2.

**Comment by UnknownLITE** [comment]
any rough ETA yet?

**Comment by nutti** [comment]
@UnknownLITE 
We don't have any schedule.
BTW, why did not you use the latest version?

**Comment by nutti** [comment]
New version which includes fake-bpy-module-4.2 is released now.
