### ISSUE TITLE
Usage instructions need to be improved

### ISSUE THREAD

**Issue by cmbasnett** [nutti/fake-bpy-module#3]
There are a number of important missing details on the usage instructions in the README.

# Missing build step
The requirement to actually build the Blender project is not expressed. There should be a one-liner build step (e.g. on Windows, `make.bat full`) that should be included in the steps.

# Missing dependencies
There are a couple of pip installations that need to be completed, namely:

```
pip install pathlib
pip install sphinx
```

# Python Version specification
Running `gen.py` with Python 2.7.12 results in the following error:
![image](https://user-images.githubusercontent.com/5035660/39462963-0decfcb2-4cca-11e8-912c-adcb139d0634.png)
It looks like the file is meant to be run on Python 3. Either this needs to be stated explicitly or, alternatively, it could be made backwards compatible by simply removing the `pathlib` dependency. It's only used in one spot in the script, and it just performs a trivial `mkdir` that could be performed with the builtin modules.

Thank you for the script! Lots more people would probably get into the Blender scripting if it was made easier to get this up and running. I would't mind helping out and making some guides for setting up these files in the various IDEs. Let me know if you'd be interested. Take care!

**Comment by nutti** [comment]
Thanks for your great feedback.

> The requirement to actually build the Blender project is not expressed. There should be a one-liner build step (e.g. on Windows, make.bat full) that should be included in the steps.

Umm, this procedure is not needed in my environment.
I used the production version, so I did not write any document to build blender itself.
But your feedback is good for the people who builds the blender by themselves.

> It looks like the file is meant to be run on Python 3. Either this needs to be stated explicitly or, alternatively, it could be made backwards compatible by simply removing the pathlib dependency.
> It's only used in one spot in the script, and it just performs a trivial mkdir that could be performed with the builtin modules.
> Thank you for the script! Lots more people would probably get into the Blender scripting if it was made easier to get this up and running. I would't mind helping out and making some guides for setting up these files in the various IDEs. Let me know if you'd be interested. Take care!

Sure.
Contributions to this project are always welcome.
Feel free to send me Pull Request if you have any ideas.

**Comment by nutti** [comment]
@cmbasnett 

Hi,

> I would't mind helping out and making some guides for setting up these files in the various IDEs. Let me know if you'd be interested. 

Any update about this?

If you have improvements about this, you can contribute to this project via pull request.
And it seems that your forked branch has some improvements.

Thanks.

**Comment by nutti** [comment]
- [ ] Missing build step
- [ ] Missing dependencies
- [ ] Python Version specification

**Comment by nutti** [comment]
Now, building step is only to execute the shell script `gen_module.sh`

https://github.com/nutti/fake-bpy-module/blob/master/src/gen_module.sh

The tutorial is available on https://github.com/nutti/fake-bpy-module/blob/master/docs/generate_modules.md

**Comment by nutti** [comment]
> Missing dependencies
> Python Version specification

Added above items to documents.

**Comment by simon50keda** [comment]
There is missing requirements for sphinx-build dependency. I followed tutorial and got module not found sphinx-build then installed it via distro package manager and it worked.
