### ISSUE TITLE
Some rna_enum references are not refined

### ISSUE THREAD

**Issue by JonathanPlasse** [nutti/fake-bpy-module#301]
### Expected behavior

All rna_enum references should be refined to a literal type.

### Description about the bug

`bpy.app.is_job_running()` and `bpy.props.(Bool|Int|Float|…)Property)()` have enum arguments that are not refined correctly.
These are the only case found by the regex ``:arg.* :ref:`rna``.

We could either update the Blender documentation upstream or special case it.

### Screenshots/Files
![Screenshot from 2024-08-11 19-07-38](https://github.com/user-attachments/assets/b98b390e-7ecd-4bc2-afc2-fac190a1bbc3)
![Screenshot from 2024-08-11 19-08-05](https://github.com/user-attachments/assets/ebce4afd-53ea-4868-b2b3-86d0c92759f1)

**Comment by nutti** [comment]
To check if the patch is approved or not, I submitted the PR instead of tweaking our generation code.
https://projects.blender.org/blender/blender/pulls/126431

**Comment by nutti** [comment]
The PR is not welcomed by the official repo.
I will tackle this from the fake-bpy-module side.

**Comment by nutti** [comment]
This issue is now solved.
I will close this issue.
