### ISSUE TITLE
Non-optional types should not have None as their default value

### ISSUE THREAD

**Issue by JonathanPlasse** [nutti/fake-bpy-module#302]
### Expected behavior

Non-optional types should have `...` as default value instead of `None`.

### Description about the bug

Having `None` as the default value for a none optional type raise a Pyright error.

### Screenshots/Files
![Screenshot from 2024-08-11 19-15-08](https://github.com/user-attachments/assets/87ab4af5-d938-4471-b40a-33c705de7870)
![Screenshot from 2024-08-11 19-16-50](https://github.com/user-attachments/assets/781e5a29-68a6-4ba1-86c1-d5eb4c91e56d)

**Comment by nutti** [comment]
This issue is now fixed.
