### ISSUE TITLE
Return value of BoneCollections.get() is not typed

### ISSUE THREAD

**Issue by arcusmaximus** [nutti/fake-bpy-module#309]
Using fake-bpy-module version 20240924.

```
bl_armature = cast(bpy.types.Armature, bl_armature_obj.data)
bl_bone_collection = bl_armature.collections.new(group_name)   # Variable gets correctly typed as BoneCollection
bl_bone_collection = bl_armature.collections.get(group_name)   # Error - variable type is unknown
```

The same thing goes for iteration:

```
for bl_bone_collection in bl_armature.collections:   # bl_bone_collection is typed as Any
    pass
```

(Both of these worked in the older version I was using before. At the same time, though, a whole bunch of `cast()` calls in my code have become unnecessary with the new version, which is great. I saw you even added types for string enums like operator return values. Thank you again for your efforts!)

**Comment by nutti** [comment]
@arcusmaximus 

Could you tell me the version which works correctly?

**Comment by nutti** [comment]
`get` method is inherited from the `bpy_struct` class and returns unidentified data type.
Due to this reason, `cast` is required for `get` method and `for ... in ...`.

I'm curious that there was a version which works without type hinting.

**Comment by arcusmaximus** [comment]
It works in fake-bpy-module-4.0 and doesn't work as of fake-bpy-module-4.1. In 4.0, `BoneCollections` derives from `bpy_prop_collection[BoneCollection]`.

**Comment by nutti** [comment]
Could you share the fake-bpy-module version (like 20240708) not the Blender version.

**Comment by nutti** [comment]
From the document, deriving `bpy_struct` is correct.
https://docs.blender.org/api/4.0/bpy.types.BoneCollections.html#bonecollections-bpy-struct

**Comment by arcusmaximus** [comment]
https://pypi.org/project/fake-bpy-module-4.0/#history
20240604 apparently.

To be specific, BoneCollections derived from both `bpy_prop_collection[BoneCollection]` *and* `bpy_struct` in that version.

**Comment by nutti** [comment]
@arcusmaximus 

Thank you. I can find this is a bug.
Fixed it now.
