### ISSUE TITLE
step by step video showing how to generate for daily builds

### ISSUE THREAD

**Issue by 3diuk** [nutti/fake-bpy-module#31]
Hi, any chance of a video walkthrough showing how to generate the necessary files to get this compatible with the daily builds?  Working on 2.9 and I think there have been some api changes since 2.82.

Cheers
Michael.

**Comment by nutti** [comment]
@3diuk 

This is hard to show the general ways to generate fake modules.
You need to check below files and add some codes.

* https://github.com/nutti/fake-bpy-module/blob/master/src/gen.py#L13-L15
* https://github.com/nutti/fake-bpy-module/tree/master/src/mods

If you don't mind, I can add a way to generate fake bpy modules for latest version (i.e. master branch).
https://github.com/nutti/fake-bpy-module/blob/master/docs/generate_modules.md

**Comment by 3diuk** [comment]
that'd be great.  If you could just download the blender source code into a specific directory and then have a one click solution to build the fake module from that, that would be awesome.

**Comment by nutti** [comment]
@3diuk 

> I can add a way to generate fake bpy modules for latest version (i.e. master branch).

I found this feature already exist.
https://github.com/nutti/fake-bpy-module/blob/master/docs/generate_modules.md#case-1-use-utility-script

I think below command sequence outputs latest fake modules.

```bash
(Download to blender-bin)
git clone git://git.blender.org/blender.git
git clone https://github.com/nutti/fake-bpy-module.git
cd fake-bpy-module/src
sh gen_module.sh ../../blender ../../blender-bin master out
```

One click solution seems good, but you can create .bat script or .sh script if you need.
I think it is already simple procedure.
Do you still need to add some solutions about this issue?

**Comment by nutti** [comment]
@3diuk 

Are there any comments about this?

**Comment by nutti** [comment]
Updated the documents and supported generation in master branch.
