### ISSUE TITLE
need an update for fake-bpy-module-4.2 that allows Python < 3.12

### ISSUE THREAD

**Issue by futurewasfree** [nutti/fake-bpy-module#313]
Subj :)

**Comment by nutti** [comment]
Already there.
https://github.com/nutti/fake-bpy-module/commit/6a1447cb87f8a646f4c6e362d527c1b2c7c9f122

We have not just released yet for the package for the individual version.
I recommend you to use `fake-bpy-module` not `fake-bpy-module-4.2` when you want to use the latest one.
