### ISSUE TITLE
All versioned releases of fake-bpy-module require Python 3.12

### ISSUE THREAD

**Issue by henrikwilhelmsen** [nutti/fake-bpy-module#314]
### Expected behavior

Either require Python >3.8 as the main release does, or the same as the Blender version the release targets.

### Description about the bug

All releases of the fake-bpy-module package on PyPi currently require Python 3.12 while the main release still requires >3.8

### Screenshots/Files [Optional]

![image](https://github.com/user-attachments/assets/4a10bd3b-b931-4fb7-9d73-37e8876eddac)

![image](https://github.com/user-attachments/assets/0d24a51d-80a3-4dc4-8b5a-d6db31c324c4)

![image](https://github.com/user-attachments/assets/dc6c7276-e4b1-47d0-b9f9-d9dd39293ca3)

**Comment by nutti** [comment]
Same as #313
