### ISSUE TITLE
`SpaceNodeEditor.tree_type` - incorrect typing `Literal['DUMMY']"`

### ISSUE THREAD

**Issue by Andrej730** [nutti/fake-bpy-module#317]
See example below (can be executed in default Blender session). 
`tree_type` has value `"ShaderNodeTree"` in that case but it's typed as `Literal['DUMMY']"`.
Not sure what's the correct typing for this - don't know if there's some more detailed enum for this or it should be just `str`.

```python
import bpy

space = bpy.data.screens['Shading'].areas[3].spaces.active
assert isinstance(space, bpy.types.SpaceNodeEditor)
print(space.tree_type) # ShaderNodeTree

# Type of "space.tree_type" is "Literal['DUMMY']"
reveal_type(space.tree_type)
```

**Comment by nutti** [comment]
It seems correct from the internal definition.
https://github.com/blender/blender/blob/1732467bc6925bf0e0f541f72e34b94c291d7fea/source/blender/makesrna/intern/rna_space.cc#L7806-L7809

Close this issue for now.

**Comment by Andrej730** [comment]
I guess it's an issue upstream then..
