### ISSUE TITLE
AttributeError: module 'bpy.types' has no attribute 'VIEW3D_HT_header'

### ISSUE THREAD

**Issue by grische** [nutti/fake-bpy-module#32]
**System Information**
  
* OS: Windows
* Blender version: 2.8x

**Expected behavior**  
I expect for this attribute to exist: https://github.com/blender/blender/blob/9385d887d17c529059d9f60008dc08fcec1d295f/release/scripts/startup/bl_ui/space_view3d.py#L7397-L7414

**Description about the bug**  
```
python.exe
Python 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:37:02) [MSC v.1924 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import bpy
>>> bpy.types.VIEW3D_HT_header
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'bpy.types' has no attribute 'VIEW3D_HT_header'
```

**Additional comments** [Optional]
I am not sure if I am using this module in an unintended way, but I simply tried to lint the following code: https://github.com/blender/blender/blob/a921a4daad437e8ef00adc1f7076449a7cf505e0/intern/cycles/blender/addon/ui.py#L2360-L2370

**Comment by nutti** [comment]
@grische 

Thanks.
At fast glance, it seems the issue of fake-bpy-module.
I will check it.

**Comment by nutti** [comment]
This issue is now fixed.
The fixed version will be released in few days.
