### ISSUE TITLE
Unable to autocomplete using fake-bpy-module in PyCharm Community

### ISSUE THREAD

**Issue by Yulit-c** [nutti/fake-bpy-module#322]
### System Information

* OS: [Windows11 24H2 26100.2454]
* Blender version: [4.2 or later]

### Expected behavior

The latest Blender Python API autocomplete works with the latest version of PyCharm that can currently be installed.

### Description about the bug

1. I have made the PyCharm Community 2024.3 interpreter aware of Python 3.12.
2. I installed fake-`bpy-module-latest` in the site-packages recognized by its Python interpreter using PIP.
3. However, PyCharm does not complement Blender Python code.
4. If the same interpreter is recognized by VS Code and code is written, auto-completion works correctly.

### Screenshots/Files [Optional]
![image](https://github.com/user-attachments/assets/e80de799-fb89-454f-93b0-10ff9418288b)
![image](https://github.com/user-attachments/assets/65fdf324-3a33-411a-8490-b83ad200d12d)

**Comment by Andrej730** [comment]
@Yulit-c 
Have you tried to change max filesize, as described in readme?

**Comment by Yulit-c** [comment]
When I created this Issue, I had set intellisense.filesize to 5000 but intellisense did not work.
I set it to a value greater than 7500 and it works.
Thank you.

![image](https://github.com/user-attachments/assets/a90c279a-e4f1-40bf-9f2a-9e7294e1b940)

**Comment by Andrej730** [comment]
Perhaps value in readme should be readjusted to 7000 (currently the largest file is `bpy/types/__init__.pyi` - it's 6438KB).
It's kind of annoying that PyCharm doesn't have any warnings for this...

**Comment by nutti** [comment]
Close this issue because the workaround already exists.
