### ISSUE TITLE
mathutils types `__init__` is missing argument types

### ISSUE THREAD

**Issue by Andrej730** [nutti/fake-bpy-module#324]
```python
from mathutils import Matrix, Vector, Euler, Color

Matrix(["str"])
Vector(["str"])
Euler(["str"])
Color(["str"])
```

E.g. `Matrix`'s `rows` argument has no type:
![image](https://github.com/user-attachments/assets/37513c2b-7c8f-4717-96f4-8d8b9c7269b8)

Though it is provided in the Blender docs (https://docs.blender.org/api/current/mathutils.html#mathutils.Matrix):
![image](https://github.com/user-attachments/assets/653c0a3c-ad1e-4776-adb6-e31381d018fa)

**Comment by Andrej730** [comment]
Similar:
![image](https://github.com/user-attachments/assets/115243c3-9449-4df0-963d-b987bb8c510d)

Snippet:
```python
import mathutils

vectors = (0,0,0), (1,0,0), (0,1,0)
n = mathutils.geometry.normal(vectors)
print(n)
```

Docs https://docs.blender.org/api/current/mathutils.geometry.html#mathutils.geometry.normal:
![image](https://github.com/user-attachments/assets/ecd1663e-3734-424c-ba37-174a56b219d4)

**Comment by nutti** [comment]
Now fixed.
