### ISSUE TITLE
`bpy.props` callbacks are missing detailed typing

### ISSUE THREAD

**Issue by Andrej730** [nutti/fake-bpy-module#325]
E.g. `BoolProperty` callbacks are defined as just `Callable`

![image](https://github.com/user-attachments/assets/9dec49bd-aa61-4fca-8973-90f2683f6afc)

Though they do have detailed typing in Blender docs - https://docs.blender.org/api/current/bpy.props.html#bpy.props.BoolProperty

![image](https://github.com/user-attachments/assets/658e72fd-0059-421c-8c1d-1db21a13a346)

**Comment by nutti** [comment]
This issue is now fixed.

**Comment by Andrej730** [comment]
@nutti 
There is an issue with vector properties - I believe it's misinterpreting the ellipsis in `tuple[xxx, ...]` as `int`:
![image](https://github.com/user-attachments/assets/8c4553b8-cfb4-43a7-ab79-3f77df347332)

Blender docs:
![image](https://github.com/user-attachments/assets/b3cd077c-8d69-43f1-97ee-4ca8980072c0)

Everything else can confirm as fixed.

**Comment by nutti** [comment]
> There is an issue with vector properties - I believe it's misinterpreting the ellipsis in `tuple[xxx, ...]` as `int`

This issue is also fixed.
