### ISSUE TITLE
context argument in draw() function is never optional

### ISSUE THREAD

**Issue by JonathanPlasse** [nutti/fake-bpy-module#328]
### System Information
* fake-bpy-module-latest: v20241221

### Expected behavior

`context` parameter in the `Panel.draw()` should have the type annotation `Context`

### Description about the bug

`context` parameter in the `Panel.draw()` has the type annotation `Context | None`.
All `context` parameter seems concerned by this bug not just `Panel.draw()`.

### Screenshots/Files [Optional]

![image](https://github.com/user-attachments/assets/64cd67e4-58a0-48ef-a24d-b811821f5e04)

**Comment by nutti** [comment]
Same as https://github.com/nutti/fake-bpy-module/issues/254#issuecomment-2247845038
Is it all the same for others which accept bpy.types.Context as arguments?

**Comment by JonathanPlasse** [comment]
I would say yes, in my experience `context` is never `None` is this case.

**Comment by nutti** [comment]
This issue is now fixed.
