### ISSUE TITLE
bpy.context should not be optional

### ISSUE THREAD

**Issue by JonathanPlasse** [nutti/fake-bpy-module#331]
### System Information

* fake-bpy-module: v20241221

### Expected behavior

`bpy.context` should have the type `Context`.

### Description about the bug

`bpy.context` has the type `Context | None`.

### Screenshots/Files [Optional]

![image](https://github.com/user-attachments/assets/304483d7-8fef-49fd-a259-b96ec0eaaa20)

**Comment by nutti** [comment]
From the discord channel discussion, KlassyKat said `bpy.context` may become `None`.

https://discord.com/channels/1253846991188791418/1253848264483147778/1305039971614326845

> Pythons type checking ecosystem is a bit of a mess. And I believe the python types are generated from cpp functions which leaves a lot of gaps so some of the best advice I can give you for setting up your dev environment for blender dev is don't go looking for perfect type checking, it will be a waste of your time.
> 
> That being said this particular thing you are referring to is very intentional though it kinda goes against the grain of how fast and loose python code usually is in terms of error handling. What is happening here, and will happen in a lot of places is that the call for bpy.context could potentionally fail to return, so it's type should be Context or None as it is. You can handle this by having a line to return an error if context is None and the typecheckers context will understand that after that line that variable can be only of type Context

I think this should not be fixed because we also need to handle the corner case.

**Comment by JonathanPlasse** [comment]
Thanks

**Comment by nutti** [comment]
From the discussion on the Discord channel, `bpy.context` will be `None` when Blender has a bug.
So, I opened this issue and will change data type `bpy.types.Context` from `bpy.types.Context | None`.

**Comment by nutti** [comment]
This issue is now fixed.
