### ISSUE TITLE
Support for Blender 2.83

### ISSUE THREAD

**Issue by grische** [nutti/fake-bpy-module#35]
**Description about the feature**  
Blender 2.83 has been released:
* https://www.blender.org/download/releases/2-83/
* https://wiki.blender.org/wiki/Reference/Release_Notes/2.83

**Comment by nutti** [comment]
@grische 

I think this update is needed.
After tackling to make new docker image, I will tackle this.

**Comment by nutti** [comment]
This feature is now merged into master branch.
Also, all tests are passed in CI.
