### ISSUE TITLE
Add support for UPBGE

### ISSUE THREAD

**Issue by mysticfall** [nutti/fake-bpy-module#36]
**Description about the feature**  
*The description about the feature. It is good to clear who will benefit with this feature.*
For now, there is no clear option to get autocompletion support for UPBGE, which is a popular continuation of the obsolete BGE.

As such, it would help those who are new to UPBGE, if this project could be used to generate API stubs for the platform.

**Are you willing to contribute about this feature. (Yes/No)**  
Yes, if I'm able.

**Comment by nutti** [comment]
@mysticfall 

Nice catch! Thanks.
Supporting UPBGE is good idea.

Unfortunately, I'm not familiar with UPBGE, so please advice me.

* I think UPBGE is a fork of Blender. So, should we separate module (e.g. fake-bge-module)?
* Is UPBGE Python API located on https://upbge-docs.readthedocs.io/en/latest/ ?

**Comment by mysticfall** [comment]
I think you are right in both of the assumptions. But I only just started using UPBGE (hence, my desire to have autocompletion for its API) so I posted the link to this discussion over their Discord channel to invite those more knowlegeable with the subject to the discussion.

**Comment by nutti** [comment]
@mysticfall 

Thanks.
Recently, this project suddenly starts to increase communication.
Is it good for you to make a discord or slack channel about fake-bpy-module project?

cc: @grische

**Comment by mysticfall** [comment]
I'd be willing to participate in such a channel, although I can probably only provide feedback as a user for now, as a beginner of scripting Blender.

**Comment by nutti** [comment]
@mysticfall 

Hi, I made a slack channel for fake-bpy-module.
Is it possible to send an invitation to your gmail address?

**Comment by mysticfall** [comment]
@nutti Yes, please. And thank you for offer! :)

**Comment by nutti** [comment]
@mysticfall 

Thanks. If you want, you can invite another people related to UPBGE.
I think #bge channel is good place to discuss.

**Comment by nutti** [comment]
@mysticfall 

I launched [fake-bge-module](https://github.com/nutti/fake-bge-module) project, and released [first version](https://github.com/nutti/fake-bge-module/releases/tag/20200710).

I close this issue for now.  
If you have any issue about fake-bge-module, feel free to [create issue](https://github.com/nutti/fake-bge-module/issues).
