### ISSUE TITLE
Building on Ubuntu 18.04 broken

### ISSUE THREAD

**Issue by grische** [nutti/fake-bpy-module#37]
**System Information**
  
* OS: Ubuntu 18.04

**Expected behavior**  
I would like to build the module locally

**Description about the bug**  
Expecting `python` to be the default link is inconsistent with almost all Linux distributions.
Triggered by https://github.com/nutti/fake-bpy-module/commit/c967e15002e1816bc9b14dcbaaf6c2c8159d0b3b#diff-8ccf467b925de74b5b733bc3a5c50be8

I expect it to run locally without modification.

**Comment by nutti** [comment]
@grische 

Understood your intention. Thanks for handling other distributions!
I think we should make a document for using other Python interpreter.
e.g. https://github.com/nutti/fake-bpy-module/blob/master/docs/generate_modules.md#4-run-script

For example...

```bash
PYTHON_BIN=/path/to/python3.7 bash gen_module.sh <source-dir> <blender-dir> <branch/tag/commit> <output-dir> <mod-version>
```

What do you think this idea?

**Comment by grische** [comment]
@nutti I think it is a good idea to add this to the documentation. I probably prefer to use venv with python3.7, so the user can also install all requirements from `requirements.txt`.

Similar to what I did in this comment:
https://github.com/nutti/fake-bpy-module/pull/33#issuecomment-644268778

**Comment by nutti** [comment]
The document is now merged into master branch.
