### ISSUE TITLE
AttributeError: type object 'VIEW3D_HT_header' has no attribute 'append'

### ISSUE THREAD

**Issue by grische** [nutti/fake-bpy-module#48]
**System Information**
  
* OS: Windows
* Blender version: 2.8x
* fake-bpy-module version: `fake_bpy_module_2.82-20200620` (built from current master)

**Expected behavior**  
I expect for this attribute to exist. Here is the code path for `append`:
1. https://github.com/blender/blender/blob/9385d887d17c529059d9f60008dc08fcec1d295f/release/scripts/startup/bl_ui/space_view3d.py#L552-L554
1. https://github.com/blender/blender/blob/d46273563e684bf8445369bd03752ceebf26e1ec/release/scripts/modules/bpy_types.py#L861-L862
1. https://github.com/blender/blender/blob/d46273563e684bf8445369bd03752ceebf26e1ec/release/scripts/modules/bpy_types.py#L822-L831

**Description about the bug**  
```
python.exe
Python 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:37:02) [MSC v.1924 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import bpy
>>> bpy.types.VIEW3D_HT_header
<class 'bpy.types.VIEW3D_HT_header'>
>>> bpy.types.VIEW3D_HT_header.append() 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'VIEW3D_HT_header' has no attribute 'append'
```

**Additional comments** [Optional]
This is a follow-up of #32 . 

I am still trying to lint the following code: https://github.com/blender/blender/blob/a921a4daad437e8ef00adc1f7076449a7cf505e0/intern/cycles/blender/addon/ui.py#L2360-L2370

**Comment by nutti** [comment]
This issue is now resolved.
