### ISSUE TITLE
missing __all__ in __init__ files in premade modules

### ISSUE THREAD

**Issue by asaflotz** [nutti/fake-bpy-module#5]
this way pycharm itellij can't autocomplete subdirs.
example:
when doing `import bpy` then `bpy.ops` can't be autocomplete, and also any other subdir or sub-subdir...

great feature and great README by the way!!! helped me a lot.

**Comment by nutti** [comment]
@asaflotz 

Thanks for your report.

Now, I fixed the problem you reported.
I will recreate premade module in few days.
For now, I fixed the generation script.

**Comment by nutti** [comment]
I remade all premade scripts to import submodules.
