### ISSUE TITLE
Support Blender LTS versions (currently 2.83.1)

### ISSUE THREAD

**Issue by grische** [nutti/fake-bpy-module#59]
**Description about the feature**  
Blender changed to a new release scheme, creating [an "LTS" version of Blender](https://code.blender.org/2020/02/release-planning-2020-2025/) (currently 2.83 LTS) with regular maintenance fixes. The most recent release is 2.83.1:
https://www.blender.org/press/blender-2-83-1-lts/

I am not sure if you intend to release `fake-bpy-module` for version "2.83.0", "2.83.1", ... or if you only want to have one version "2.83" and always try to stay up to date.

What is your idea here?

If you only want one version, then this Feature Request is simply a request for a version bump.

**Comment by nutti** [comment]
@grische 

fake-bpy-module only supports latest version, so a version bump is enough.
c.f. https://github.com/nutti/fake-bpy-module/blob/0040c3b2e87ae24d51f662e09269fa8ee00d2648/tools/utils/download_blender.sh#L11-L53

If you want to create PR, I will wait.
Thanks!

**Comment by grische** [comment]
I can work on it after #51 has landed. I would like to have one pip package for 2.83.0 before upgrading.
