### ISSUE TITLE
Allow using strings as bpy_prop_collection indices

### ISSUE THREAD

**Issue by MoritzBrueckner** [nutti/fake-bpy-module#76]
**Description about the feature**

When using `bpy_prop_collection`, PyCharm warns about lines like this:
```python
bpy.data.worlds['WorldName']
```

It doesn't expect using a string as the index instead of an int or slice (`Unexpected type(s):(str)Possible types:(int)(slice)`), probably because `bpy_prop_collection` only exists for documentation purposes and thus has no `__getitem__`/`__setitem__` methods.

I'm not sure how difficult it would be to append those methods after the modules are generated.

**Comment by nutti** [comment]
@MoritzBrueckner 

Thanks for your report.

`bpy_prop_collection` is now handled as `list`.
So, we could not handle string for now.

I think we may solve this problem by handling this as `dict[str, XXX]`.
What do you think?

**Comment by MoritzBrueckner** [comment]
Hm, the issue with this is that you can also access prop collections via int indices and probably also via slices (didn't test that), so that functionality would be broken then. There are cases where it makes sense to use integers, for example to get the last added object of a collection with `[-1]`.

A few ideas (for which I don't know if they are actually viable):
- Using 
  ```python
  typing.Union[typing.List['World'], typing.Dict[str, 'World'], 'bpy_prop_collection', 'BlendDataWorlds']
   ```
  instead of
  ```python
  typing.Union[typing.List['World'], 'bpy_prop_collection', 'BlendDataWorlds']
   ```

- ```python
  typing.Union[typing.Dict[typing.Union[str, int], 'World'], typing.Dict[str, 'World'], 'bpy_prop_collection', 'BlendDataWorlds']
   ```
  (Probably bad, no support for slices)

- Or, would it work to add `__getitem__`/`__setitem__` methods to `bpy_prop_collection`? That would "break" the return type, right? Then maybe add it to all `BlendDataXXX` types?

If there is no other solution than the one you've suggested, I would indeed choose this over int indices as strings are probably used more often (?).

Thank you!

**Comment by nutti** [comment]
@MoritzBrueckner 

Oh, sorry for my poor explanation.

```python
typing.Union[typing.List['World'], typing.Dict[str, 'World'], 'bpy_prop_collection', 'BlendDataWorlds']
```

Yes, my solution intended above type hint.

In theory, `__getitem__`, `__setitem__` also looks good to me.
But it is difficult to include these logic to our generation scripts.

**Comment by MoritzBrueckner** [comment]
That does the work, just tested it :)

However, the returned type of `bpy.data.worlds["someworld"]` now is `Union[list, World]` instead of just `World` when using an int index. I have no idea why.

**Comment by nutti** [comment]
@MoritzBrueckner 

Thanks for your feedback!
Is it still same when you add `__getitem__` and `__setitem__` ?

**Comment by MoritzBrueckner** [comment]
Unfortunately yes. I think the issue is that the dict-like access is also working for some other function that returns a list, maybe one of `items()`, `keys()` or `values()` in `bpy_prop_collection`. When I undo my changes so that the warning comes back, the returned type is a list.

**Comment by nutti** [comment]
Hmm,

I think this seems difficult to solve.
BTW, I will try to fix as follows for now.

```python
typing.Union[typing.List['World'], typing.Dict[str, 'World'], 'bpy_prop_collection', 'BlendDataWorlds']
```

I think this is not complete solution, but some issues will be solved.
What do you think about this?

**Comment by MoritzBrueckner** [comment]
Yes, I think this is the best for now. For me personally it's more annoying to have that warning message mentioned in the first post than to have some auto-completion options for lists that don't work. Hopefully there will some better solution eventually.

Thank you for your efforts and for this awesome package!

**Comment by nutti** [comment]
This issue is now fixed.

**Comment by MoritzBrueckner** [comment]
Thank you very much!

**Comment by MicaelJarniac** [comment]
Wouldn't it be better to add a `__getitem__` method to `bpy_prop_collection`, that accepts both `str` and `int`, instead of faking it by typing it as `List` and `Dict`? I've come across a bug related to this.
