### ISSUE TITLE
include module as external lib- better explanation here:

### ISSUE THREAD

**Issue by asaflotz** [nutti/fake-bpy-module#8]
in fake-bpy-module/docs/setup_pycharm.md:
maybe you should point to this answer or copy and refer it...
https://stackoverflow.com/a/36492328/4879610

**Comment by nutti** [comment]
Thanks.
I will check it and refer.

**Comment by MichaelMay81** [comment]
You could extend the description to per project-setup:
1. In the PyCharm main menu select: File – Settings
2. Project: The name of the current project – Project Structure
3. Click Add Content Root and add the directory with auto-complete files to list.
From: https://b3d.interplanety.org/en/using-external-ide-pycharm-for-writing-blender-scripts/

**Comment by nutti** [comment]
@asaflotz @MichaelMay81 

Thanks for the useful documents.
I updated the documents.
