### ISSUE TITLE
Integration with linters

### ISSUE THREAD

**Issue by aviggiano** [nutti/fake-bpy-module#82]
Hello! Awesome module here 👏 

I was wondering if this can be used together with linters such as `flake8`, so that it will report invalid usage of `bpy` calls.

Best

**Comment by nutti** [comment]
@aviggiano 

We are already using fake-bpy-module as a linter for CI.
https://github.com/nutti/fake-bpy-module/blob/26eb757eaa6706405b68fe6340d2cf64d60027a2/.github/workflows/fake-bpy-module-ci.yml#L115-L118

I'm not sure your problem.
Do you have any issues to use fake-bpy-module?

**Comment by aviggiano** [comment]
Sorry that I wasn't clear.
I wish use this module together with flake8 to check for invalid function calls and usage of `bpy`.

For example, if I have the following file:

```
// test.py
import bpy

class MyClass(object):
    def __init__(self):
        bpy.invalid.call()
```

and run

```
flake8 test.py
```

I get no warnings. How can I change that?

**Comment by nutti** [comment]
@aviggiano 

I think it is a problem for the usage of flake8 rather than fake-bpy-module issue.
In our pylint test, we could detect error when the API is missing.

I did a simple test with os module and execute flake8 against below script.

```bash
import os

class MyClass(object):
    def __init__(self):
        os.hoge
```

And, the result is same (with no output).
So, I think this is not a fake-bpy-module issue.

Could you check the usage or specification of flake8?

**Comment by aviggiano** [comment]
@nutti Yea I guess you are right
Sorry, I might be confusing different tools for code checking in Python (I come from TypeScript where type/code checking is mostly handled by a single lint/build step)

Nevertheless, I am still not sure how to accomplish the code checking I am looking for.
The point is: if this module provides a clear interface for `bpy` with, for example, a property called `context`, such that you can access with `bpy.context`, how can I ensure that only calls to `bpy.context` are valid? How can I prevent calls to `bpy.context2`? Is there something I can do to ensure that?

**Comment by nutti** [comment]
@aviggiano 

Sorry, I don't have enough knowledge about flake8.
I think the best way is redirecting this question to the flake8 community or other related forums.

**Comment by aviggiano** [comment]
@nutti no problem, thank you for helping!
I'll close this issue here.
