### ISSUE TITLE
Pylance Linter is unable to detect member

### ISSUE THREAD

**Issue by Kein** [nutti/fake-bpy-module#83]
**System Information**
  * OS: Win7x64
* Blender 2.8

I'm not sure if this is fake-bpy or pylance issue so I will try here for now. The issue demonstrated:
![image](https://user-images.githubusercontent.com/623756/101225822-93130b00-36a3-11eb-904b-c602c991d8ca.png)

**Comment by nutti** [comment]
@Kein 

I think `bpy_prop_collection` should have this kind of API.
Is there any other missing APIs about `bpy_prop_collection`?
I will add them when I add `new` method to `bpy_prop_collection`.

**Comment by Kein** [comment]
Looks like it is here but may be defined  in a way that annoys pylance server?
![image](https://user-images.githubusercontent.com/623756/101230923-5eaa4980-36b9-11eb-9992-1773fe17f16f.png)
![image](https://user-images.githubusercontent.com/623756/101230925-623dd080-36b9-11eb-9bcb-3f28e5e4709f.png)

Sorry, I've only meet python and its dev environment a few days ago, dont have overall knowledge to identify issue.

**Comment by nutti** [comment]
@Kein 

Ah, I could understand. Yes, you are right.
`BlendDataCollections` has a `new` method.

Then, I checked this in my VSCode environment, and there is no error.
So, I think this is a specific case for pylance.

Unfortunately, I don't have enough knowledge about pylance.
So, you should redirect this to the pylance community or other python community.

**Comment by Kein** [comment]
Fair enough.

**Comment by nutti** [comment]
I'll close this issue for now.
If another problem is raised, please feel free to open.
