### ISSUE TITLE
Missing operators and initializers, interface implementations on stubs

### ISSUE THREAD

**Issue by Kein** [nutti/fake-bpy-module#84]
**Vector2**
* Missing `__add__`

**ProgressReport**
* Missing `__init__`, `__enter__` and `__exit__`

**ProgressReportSubstep**
* Missing `__init__`, `__enter__` and `__exit__`

Also, a lot of classes missing iterators.

**Comment by nutti** [comment]
@Kein 

I think we should not support this kind of APIs in fake-bpy-module which is not part of official documentation.
We are able to support these API in some specific blender version, but we could not maintain all later blender version in future.

**Comment by Kein** [comment]
You think in theory it is possible to generate the stubs from module without the docs but with all the methods stubs and proper types for statical analisys to work?

**Comment by nutti** [comment]
@Kein 

Yes, generating the subs without the docs is possible in theory.
But, we need to fix the all generation logic to realize this.
In addition, we need to maintain this logic for the future blender version, this makes us lots of works.
Because of these reasons, we did not want to support this.

**Comment by Kein** [comment]
Okay, what about implementing proper types so the static type analyzer can be used properly? Is that doable?

**Comment by nutti** [comment]
@Kein 

>  implementing proper types so the static type analyzer can be used properly

What do you mean of this?
I think adding types manually is very costly.
