### ISSUE TITLE
Operator class lacks filepath property

### ISSUE THREAD

**Issue by Kein** [nutti/fake-bpy-module#85]
https://docs.blender.org/api/current/bpy.ops.import_mesh.html?highlight=operator%20filepath
https://docs.blender.org/api/current/bpy.ops.cachefile.html?highlight=operator%20filepath
https://docs.blender.org/api/current/bpy.types.Operator.html?highlight=operator%20filepath

```python
class MyImport(Operator, ImportHelper):
    bl_idname = "Beh"
    bl_label = "Moh"
    bl_description = "Meh"
    filename_ext = ".muh"

    def execute(self: Operator, context: Context):
        return do_thing(self, context, self.filepath)
```

In this case in current "stubs" `.filepath` does not exist

**Comment by nutti** [comment]
@Kein 

I think `bpy.ops.import_mesh` , `bpy.ops.cachefile` , `bpy.types.Operator` do not include `.filepath` member.
This is just a function.
Could you check them?

**Comment by nutti** [comment]
@Kein 

I think we should talk with you at [fake-bpy-module](https://blender.chat/channel/fake-bpy-module) channel on [blender.chat](https://blender.chat/).
The issues you reporteds need additional work, so I would like to talk with the future plan of this module.

**Comment by nutti** [comment]
I close this issue because `bpy.ops.XXX` and `bpy.types.Operator` do not include any `filename` member.
