### ISSUE TITLE
Assignment from no return Error (Blender 2.79)

### ISSUE THREAD

**Issue by kungfooman** [nutti/fake-bpy-module#86]
**System Information**
  
* OS: Windows10
* Blender version: 2.79

**Expected behavior**  
Those functions should return a proper type

**Description about the bug**  

I would like to have no errors in this plugin I want to extend in Python

**Screenshots/Files**

![image](https://user-images.githubusercontent.com/5236548/110244802-c4c89600-7f60-11eb-835e-2021b82c4bca.png)

**Additional comments**

Thanks a lot for this amazing project!

**Comment by nutti** [comment]
This issue is now fixed.

I don't have any schedules to release this version.
But you can use the fixed version from below link.
https://github.com/nutti/fake-bpy-module/actions/runs/638585926

**Comment by nutti** [comment]
@kungfooman 

Thanks for your report.
I'm very grad to help you!
