### ISSUE TITLE
Issues with VS Code

### ISSUE THREAD

**Issue by jdent02** [nutti/fake-bpy-module#9]
This project works great in PyCharm (both 2.79 and 2.8), not so much in VS Code.  In VS Code neither work, even after following the VS Code instructions exactly.  Are there some steps that haven't been documented?

**Comment by nutti** [comment]
The documents fullfils all procedures I did in VS Code.
Would you tell me the detailed issues you encountered?
I could not find the solution because I'm not an expert about VS Code.

**Comment by jdent02** [comment]
Hi Nutti.  I added the modules to the 'PythonAutocomplete:ExtraPaths' setting as the instructions said.

But I do have some additional info that might help: while I still can't get 2.79b to work in VS Code, the 2.8 module does work.  Not sure why (as I didn't do anything different).

**Comment by nutti** [comment]
@jdent02 

I understood. Thanks.
I'm curious about why fake-bpy-module does not work in Blender 2.79.
On my environment, it works fine.
Could you reopen this issue or make new issue if you have any more problem.
Thanks for your investigation!
