### ISSUE TITLE
Support for Blender 2.93

### ISSUE THREAD

**Issue by azamzubairi** [nutti/fake-bpy-module#90]
**Description about the feature**  

**Blender 2.93 has been released**:

https://www.blender.org/download/releases/2-93/
https://wiki.blender.org/wiki/Reference/Release_Notes/2.93

**Comment by nutti** [comment]
@azamzubairi 

We have already finished the testing for this.
https://github.com/nutti/fake-bpy-module/actions/runs/969975176

So, we will release fake bpy module for Blender 2.93 soon.

**Comment by azamzubairi** [comment]
Ok thanks.

**Comment by nutti** [comment]
bpy-fake-module-2.93 is now released with the newest release.

https://github.com/nutti/fake-bpy-module/releases/tag/20210701
