### ISSUE TITLE
Fix for bpy.types intelliSense in PyCharm or better documentation

### ISSUE THREAD

**Issue by STRONG-MAD** [nutti/fake-bpy-module#91]
* OS: Windows
* Blender version: 2.9.3

I have both this package and `bpy` installed through pip.

Installing this package isn't enough to fix all `bpy` intelliSense in PyCharm.
Some modules like `bpy.types` have the issue of being too big for intelliSense to work, thus omitting them from intelliSense.

The fix for PyCharm -

Is to go to the PyCharm's `idea.properties` file and changing the value of `idea.max.intellisense.filesize`.
To a value that supports the size of the module.

It would be great to have this documented here or even better be able to do this automatically.

**Comment by nutti** [comment]
@STRONG-MAD 

Thanks for your suggestion.

Recently, I don't use PyCharm actually. So, please comment if I mistake my understanding.
IMO, intellisense in PyCharm is processed at the first time after when the new package is found.
Is there still bottleneck of file access to the processed data for intellisense?

**Comment by STRONG-MAD** [comment]
Yeah it's as stated.

The default for Pycharm is around 2.5mb
And I think some  files like what I mentioned go over 2.6mb.

**Comment by nutti** [comment]
@STRONG-MAD 

Thanks for your reply.
I will add this information to the document.
I think this information is useful for all PyCharm users.

BTW, you can send me a pull request if you want.
Maybe, below documents must be fixed.

* https://github.com/nutti/fake-bpy-module/blob/master/README.md#install-via-pip-package
* https://github.com/nutti/fake-bpy-module/blob/master/docs/setup_pycharm.md

**Comment by nutti** [comment]
Fixed the documentation.
So, I will close this issue
