### ISSUE TITLE
Unresolved attribute references for Matrix class

### ISSUE THREAD

**Issue by charlotte-green** [nutti/fake-bpy-module#93]
```
empty = bpy.data.objects.new("Empty", None)
empty.matrix_basis.identity()
empty.matrix_parent_inverse.identity()
rot = empty.matrix_world.to_quaternion()
mx = empty.matrix_world.inverted()
transform_mx = empty.matrix_world @ empty.matrix_world.inverted()
```

Because matrices type set to typing.List[float] instead of Matrix, the code above shows "Unresolved reference" warnings in PyCharm

**Comment by nutti** [comment]
@charlotte-green 

Thanks.
But I think this issue should be solved by fixing the Blender docs.
https://docs.blender.org/api/current/bpy.types.Object.html#bpy.types.Object.matrix_world

I will send a patch in near future.

**Comment by nutti** [comment]
This is not blender issue.
I fixed now this.
