### ISSUE TITLE
bpy.ops. does not auto complete

### ISSUE THREAD

**Issue by RidaAyed** [nutti/fake-bpy-module#94]
**System Information**
  
* OS: Linux
* Blender version: 3.0

**Expected behavior**  
*Typing `o` after bpy. should autocomplete to bpy.ops*

**Description about the bug**  
Typing `o` after bpy. shows private attributes instead of `ops`.
Furthermore: *While bpy.ops does **not auto complete**, the completion **starts working again after** the non-working `ops` path e.g. bpy.ops.**mesh.***

**Screenshots/Files** [Optional]  
![GIFrecord_2022-01-02_122834](https://user-images.githubusercontent.com/20554483/147874411-44257fe0-9093-403e-8163-8318905d7d7a.gif)

**Additional comments** [Optional]

**Comment by nutti** [comment]
I could not reproduce this.
How did you install the fake-bpy-module?
Also, I would like to know the version of fake-bpy-module.

**Comment by RidaAyed** [comment]
Installed using `yay`:

`$ yay fake-bpy`

```shell
aur/python-fake-bpy-module-2.93 20210701-1 (+0 0.00) (Installed)
  Fake Blender Python API module collection for the code completion.
```
Editor:

*Emacs* 0.300.0@27.2 (spacemacs)

**Comment by nutti** [comment]
Sorry, I'm not an Emacs user.
I'm not sure that this issue comes from the differences between emacs and others.

**Comment by nutti** [comment]
We close this issue because this environment is beyond scope of supported environment.
If there are same issues from other users, I will consider to tackle this issue.
