### ISSUE TITLE
Version 3.1 not available on pypi

### ISSUE THREAD

**Issue by halirutan** [nutti/fake-bpy-module#98]
First off, thank you very much for your work. It's lovely to have code completion and documentation lookup in PyCharm for Blender code. It seems that version 3.1 is not available on pypi and the link in your README leads to an error.

Keep up the good work!

**Comment by halirutan** [comment]
Thanks. I got confused since you mention version 3.1 explicitly in the table in the README.

**Comment by nutti** [comment]
@halirutan 

Because of the lack of time, I could not support Blender 3.1 yet.
But, I will release for Blender 3.1 in near future.
Thanks for pinging me.
