### ISSUE TITLE
the type of `bpy.ops.transform.rotate(orient_matrix=)` parameter is not correct

### ISSUE THREAD

**Issue by anatawa12** [nutti/fake-bpy-module#99]
**System Information**
  
* OS: macOS
* Blender version: 2.93

**Expected behavior**  
*The behavior you expect about the feature you reported.*
type of `bpy.ops.transform.rotate(orient_matrix=)` parameter should be `List[List[float]]` (`Union[List[List[float]],Tuple[Tuple[float, float, float], Tuple[float, float, float], Tuple[float, float, float]]` can be better)

**Description about the bug**  
*The description about the bug.*

type of `bpy.ops.transform.rotate(orient_matrix=)` oaraneter should be `List[List[float]]` (`Union[List[List[float]],Tuple[Tuple[float, float, float], Tuple[float, float, float], Tuple[float, float, float]]` can be better) but `List[Float]` in fake-bpy-module

**Screenshots/Files** [Optional]  
*It is good to solve the bug if you attach the screenshots or .blend file.*

**Additional comments** [Optional]

**Comment by anatawa12** [comment]
I found that it looks this is more generic problem, parameters accepts matrix should be marked as `List[List[float]]` but currently `List[float]`.

**Comment by nutti** [comment]
This relates to #95 .
Current analysis algorithm does not support this kind of types.
I think this should be fixed.
